[package]
name = "saffron"
version = "0.1.0"
description = "The Saffron programming language"
authors = ["henry232323"]
entry = "src/compiler/main.sf"

[dependencies]

[scripts]
bootstrap = "./bootstrap.sh"
bootstrap-full = "./bootstrap.sh --verbose"
build = "./bootstrap.sh"
test = "saffron run tools/run_tests.sf"
docs = "cd docs && mdbook build"
lint = "saffron run tools/lint.sf --check src/"
lint-fix = "saffron run tools/lint.sf --fix src/"
