[workspace]
members = ["frontend"]

[package]
name = "bazaar"
version = "0.1.0"
description = "Bazaar — the Saffron package registry"
entry = "src/main.sf"
authors = ["henry232323"]

[dependencies]

[scripts]
build = "cd frontend && pantry build && cd .. && saffron build src/main.sf -o build/bazaar"
dev = "saffron run dev.sf"
frontend = "cd frontend && pantry build"
migrate = "saffron run src/migrate.sf"
start = "./build/bazaar"
