; Generated by Saffron LLVM compiler
target triple = "arm64-apple-macosx15.0.0"

@.str.0 = private unnamed_addr constant [7 x i8] c"hello \00"
@.str.1 = private unnamed_addr constant [6 x i8] c"world\00"

declare i32 @puts(i8*)
declare i32 @printf(i8*, ...)
declare i32 @snprintf(i8*, i64, i8*, ...)
declare i8* @malloc(i64)
declare i8* @realloc(i8*, i64)
declare void @free(i8*)
declare i64 @strlen(i8*)
declare i8* @strcpy(i8*, i8*)
declare i8* @strcat(i8*, i8*)
declare i8* @strstr(i8*, i8*)
declare i32 @strcmp(i8*, i8*)
declare i32 @strncmp(i8*, i8*, i64)
declare i64 @atol(i8*)
declare void @exit(i32)
declare i8* @fopen(i8*, i8*)
declare i64 @fread(i8*, i64, i64, i8*)
declare i64 @fwrite(i8*, i64, i64, i8*)
declare i32 @fclose(i8*)
declare i32 @fseek(i8*, i64, i32)
declare i64 @ftell(i8*)
declare i8* @strtok(i8*, i8*)
declare i32 @pclose(i8*)
declare i8* @popen(i8*, i8*)
declare i8* @fgets(i8*, i32, i8*)
declare void @llvm.memcpy.p0i8.p0i8.i64(i8*, i8*, i64, i1)
declare i32 @setjmp(i8*)
declare void @longjmp(i8*, i32)
declare void @__io_println_str(i64)
declare void @__io_println_int(i64)
declare void @__io_println_bool(i64)
declare void @__io_println_nil()
declare void @__io_print_str(i64)
declare void @__io_print_int(i64)
declare i64 @__bool_to_string(i64)
declare i64 @__nil_to_string()

declare i64 @__float_to_string(i64)
declare i64 @__string_eq(i64, i64)
declare i64 @__string_ne(i64, i64)
; --- NaN-boxing value helpers ---
declare i64 @__val_tag_int(i64)
declare i64 @__val_untag_int(i64)
declare i64 @__val_tag_ptr(i8*)
declare i8* @__val_untag_ptr(i64)
declare i64 @__val_tag_float(double)
declare double @__val_untag_float(i64)
declare i64 @__val_tag_bool(i64)
declare i64 @__val_untag_bool(i64)
declare i64 @__val_nil()
declare double @strtod(i8*, i8*)
declare double @llvm.floor.f64(double)

declare i64 @__division_error()
declare i64 @__null_pointer_error()
declare i64 @__runtime_error(i64)
declare i64 @__runtime_error_fatal(i64)

@.fmt.ld = linkonce_odr unnamed_addr constant [4 x i8] c"%ld\00"
@.str.empty = linkonce_odr unnamed_addr constant [1 x i8] c"\00"
@.str.rb = linkonce_odr unnamed_addr constant [2 x i8] c"r\00"
@.str.wb = linkonce_odr unnamed_addr constant [2 x i8] c"w\00"
@.str.r = linkonce_odr unnamed_addr constant [2 x i8] c"r\00"
@__argc = weak global i32 0
@__argv = weak global i8** null
@__exception_value = weak global i64 0
@__jmp_buf_current = weak global i8* null

; List = { count, capacity, data* }
%List = type { i64, i64, i64* }
; Map = { count, capacity, keys*, values* }
%Map = type { i64, i64, i64*, i64* }

; --- Runtime declarations ---
%SB = type { i64, i64, i8* }

declare i64 @__list_new()
declare i64 @__list_push(i64, i64)
declare i64 @__list_get(i64, i64)
declare i64 @__list_set(i64, i64, i64)
declare i64 @__list_length(i64)
declare i64 @__list_pop(i64)
declare i64 @__list_remove(i64, i64)
declare i64 @__list_slice(i64, i64, i64)
declare i64 @StringBuilder()
declare i64 @__sb_append(i64, i64)
declare i64 @__sb_to_string(i64)
declare i64 @__safe_strcmp(i64, i64)
declare i64 @__map_new()
declare i64 @__map_set(i64, i64, i64)
declare i64 @__map_get(i64, i64)
declare i64 @__map_has(i64, i64)
declare i64 @__map_keys(i64)
declare i64 @__str_ends_with(i64, i64)
declare i64 @__str_split(i64, i64)
declare i64 @__str_replace(i64, i64, i64)
declare i64 @__int_to_string(i64)
declare i64 @__list_join(i64, i64)
declare i64 @__join_append(i64, i64, i64, i64, i64)
declare i64 @__list_contains(i64, i64)
declare i64 @__io_read_file(i64)
declare i64 @__io_write_file(i64, i64)
declare i64 @__io_file_exists(i64)
declare i64 @__io_mkdir(i64)
declare i64 @__io_walk_dir(i64)
declare i64 @__io_append_file(i64, i64)
declare i64 @__os_exec(i64)
declare i64 @__os_args()
declare i64 @__os_cwd()
declare i64 @__os_path_sep()
declare i64 @__os_platform()
declare i64 @__os_env(i64)
declare i1 @__val_is_int(i64)
declare i1 @__val_is_float(i64)
declare i1 @__val_is_string(i64)
declare i1 @__val_is_bool(i64)
declare i1 @__val_is_nil(i64)
declare i1 @__val_is_list(i64)
declare i1 @__val_is_map(i64)

; --- GC runtime ---
declare void @__gc_enable()
declare void @__gc_disable()
declare void @__gc_collect()
declare void @__gc_set_threshold(i64)
declare i64 @__gc_stat_alloc_count()
declare i64 @__gc_stat_total_bytes()
declare i64 @__gc_stat_collections()
declare i64 @__gc_stat_freed_bytes()
declare i64 @__gc_stat_threshold()
declare void @__gc_debug_stats()
declare i64 @__gc_alloc(i64, i64)
declare i64 @__gc_alloc_zeroed(i64, i64)
declare i64 @__gc_realloc(i64, i64, i64)
declare void @__gc_push_root(i64)
declare void @__gc_pop_roots(i64)
declare i64 @__gc_shadow_stack_depth()
declare i64 @__gc_list_new()
declare void @__gc_list_push(i64, i64)
declare i64 @__gc_map_new()
declare i64 @__gc_stringbuilder_new()
declare i64 @__gc_string_alloc(i64)
declare i64 @__gc_closure_new(i64, i64)
declare i64 @__gc_env_alloc(i64)
declare i64 @__gc_instance_alloc(i64)

; --- Scheduler runtime ---
declare double @sf_time_now()
declare i64 @sf_tcp_poll(i64, i64, i64)
declare void @__sched_coro_resume(i64)
declare i64 @__sched_coro_done(i64)
declare void @__sched_coro_destroy(i64)
declare i64 @__sched_get_yield_reason()
declare i64 @__sched_get_yield_arg()
declare i64 @__sched_get_task_result()
declare void @__sched_reset_yield()
declare void @__sched_store_result(i64, i64)
declare i64 @__sched_get_stored_result(i64)
declare i64 @__sched_has_stored_result(i64)

define i64 @greet(i64 %name.arg) {
entry:
  %name = alloca i64
  store i64 %name.arg, i64* %name
  %t1 = ptrtoint i64* %name to i64
  call void @__gc_push_root(i64 %t1)
  %t2 = getelementptr [7 x i8], [7 x i8]* @.str.0, i64 0, i64 0
  %t3 = ptrtoint i8* %t2 to i64
  %t4 = load i64, i64* %name
  %t5 = inttoptr i64 %t3 to i8*
  %t6 = inttoptr i64 %t4 to i8*
  %t7 = call i64 @strlen(i8* %t5)
  %t8 = call i64 @strlen(i8* %t6)
  %t9 = add i64 %t7, %t8
  %t10 = add i64 %t9, 1
  %t11 = call i8* @malloc(i64 %t10)
  call i8* @strcpy(i8* %t11, i8* %t5)
  call i8* @strcat(i8* %t11, i8* %t6)
  %t12 = ptrtoint i8* %t11 to i64
  call void @__gc_pop_roots(i64 1)
  ret i64 %t12
}

define i64 @__saffron_main() {
entry:
  %msg = alloca i64
  store i64 0, i64* %msg
  %t1 = ptrtoint i64* %msg to i64
  call void @__gc_push_root(i64 %t1)
  %t2 = getelementptr [6 x i8], [6 x i8]* @.str.1, i64 0, i64 0
  %t3 = ptrtoint i8* %t2 to i64
  %t4 = call i64 @greet(i64 %t3)
  store i64 %t4, i64* %msg
  %t5 = load i64, i64* %msg
  call void @__io_println_str(i64 %t5)
  call void @__gc_pop_roots(i64 1)
  ret i64 0
}

define i32 @main(i32 %argc, i8** %argv) {
entry:
  store i32 %argc, i32* @__argc
  store i8** %argv, i8*** @__argv
  %main_ret = call i64 @__saffron_main()
  %exit_code = trunc i64 %main_ret to i32
  ret i32 %exit_code
}
