; Generated by Saffron LLVM compiler
target triple = "arm64-apple-macosx15.0.0"

@.str.0 = private unnamed_addr constant [22 x i8] c"list  [1,2]==[1,2] : \00"
@.str.1 = private unnamed_addr constant [22 x i8] c"list  [1,2]==[3,4] : \00"
@.str.2 = private unnamed_addr constant [2 x i8] c"a\00"
@.str.3 = private unnamed_addr constant [2 x i8] c"a\00"
@.str.4 = private unnamed_addr constant [22 x i8] c"map   {a:1}=={a:1} : \00"
@.str.5 = private unnamed_addr constant [23 x i8] c"class Box(1)==Box(1): \00"
@.str.6 = private unnamed_addr constant [22 x i8] c"list  [1,2]==\22hi\22  : \00"
@.str.7 = private unnamed_addr constant [3 x i8] c"hi\00"
@.str.8 = private unnamed_addr constant [23 x i8] c"list  []==[]        : \00"
@.str.9 = private unnamed_addr constant [22 x i8] c"list  []==\22\22       : \00"
@.str.10 = private unnamed_addr constant [1 x i8] c"\00"
@.str.11 = private unnamed_addr constant [23 x i8] c"map   {}==[]        : \00"
@.str.12 = private unnamed_addr constant [4 x i8] c"Box\00"
@.str.13 = private unnamed_addr constant [8 x i8] c"Unknown\00"
@.str.14 = private unnamed_addr constant [2 x i8] c"v\00"
@.str.15 = private unnamed_addr constant [2 x i8] c"v\00"

%Box = type { i64 }

declare i32 @puts(i8*)
declare i32 @printf(i8*, ...)
declare i32 @snprintf(i8*, i64, i8*, ...)
declare i8* @malloc(i64)
declare i8* @realloc(i8*, i64)
declare void @free(i8*)
declare i64 @strlen(i8*)
declare i8* @strcpy(i8*, i8*)
declare i8* @strcat(i8*, i8*)
declare i8* @strstr(i8*, i8*)
declare i32 @strcmp(i8*, i8*)
declare i32 @strncmp(i8*, i8*, i64)
declare i64 @atol(i8*)
declare void @exit(i32)
declare i8* @fopen(i8*, i8*)
declare i64 @fread(i8*, i64, i64, i8*)
declare i64 @fwrite(i8*, i64, i64, i8*)
declare i32 @fclose(i8*)
declare i32 @fseek(i8*, i64, i32)
declare i64 @ftell(i8*)
declare i8* @strtok(i8*, i8*)
declare i32 @pclose(i8*)
declare i8* @popen(i8*, i8*)
declare i8* @fgets(i8*, i32, i8*)
declare void @llvm.memcpy.p0i8.p0i8.i64(i8*, i8*, i64, i1)
declare i32 @setjmp(i8*) returns_twice
declare void @longjmp(i8*, i32) noreturn
declare void @__io_println_str(i64)
declare void @__io_println_int(i64)
declare void @__io_println_bool(i64)
declare void @__io_println_nil()
declare void @__io_println_any(i64)
declare void @__io_print_str(i64)
declare void @__io_print_int(i64)
declare i64 @__any_to_string(i64)
declare i64 @__bool_to_string(i64)
declare i64 @__nil_to_string()

declare i64 @__float_to_string(i64)
declare i64 @__string_eq(i64, i64)
declare i64 @__string_ne(i64, i64)
declare i64 @__any_eq(i64, i64)
declare i64 @__any_ne(i64, i64)
declare i64 @__string_intern(i64)
; --- NaN-boxing value helpers ---
declare i64 @__val_tag_int(i64)
declare i64 @__val_untag_int(i64)
declare i64 @__val_tag_ptr(i8*)
declare i64 @__val_tag_ptr_nullable(i8*)
declare i8* @__val_untag_ptr(i64)
declare i64 @__val_tag_float(double)
declare double @__val_untag_float(i64)
declare i64 @__val_tag_bool(i64)
declare i64 @__val_untag_bool(i64)
declare i64 @__rt_tag_ptr(i64)
declare double @strtod(i8*, i8*)
declare double @llvm.floor.f64(double)

declare i64 @__division_error()
declare i64 @__null_pointer_error()
declare i64 @__runtime_error(i64)
declare i64 @__runtime_error_fatal(i64)

@.fmt.ld = linkonce_odr unnamed_addr constant [4 x i8] c"%ld\00"
@.str.empty = linkonce_odr unnamed_addr constant [1 x i8] c"\00"
@.str.rb = linkonce_odr unnamed_addr constant [2 x i8] c"r\00"
@.str.wb = linkonce_odr unnamed_addr constant [2 x i8] c"w\00"
@.str.r = linkonce_odr unnamed_addr constant [2 x i8] c"r\00"
@__argc = weak global i32 0
@__argv = weak global i8** null
@__exception_value = weak global i64 0
@__jmp_buf_current = weak global i8* null

; List = { count, capacity, data* }
%List = type { i64, i64, i64* }
; Map = { count, capacity, keys*, values* }
%Map = type { i64, i64, i64*, i64* }

; --- Runtime declarations ---
%SB = type { i64, i64, i8* }

declare i64 @__list_new()
declare i64 @__list_push(i64, i64)
declare i64 @__list_get(i64, i64)
declare i64 @__list_set(i64, i64, i64)
declare i64 @__list_length(i64)
declare i64 @__list_pop(i64)
declare i64 @__list_remove(i64, i64)
declare i64 @__list_slice(i64, i64, i64)
declare i64 @StringBuilder()
declare i64 @__sb_append(i64, i64)
declare i64 @__sb_to_string(i64)
declare i64 @__safe_strcmp(i64, i64)
declare i64 @__map_new()
declare i64 @__map_set(i64, i64, i64)
declare i64 @__map_get(i64, i64)
declare i64 @__map_has(i64, i64)
declare i64 @__map_keys(i64)
declare i64 @__str_ends_with(i64, i64)
declare i64 @__str_split(i64, i64)
declare i64 @__str_replace(i64, i64, i64)
declare i64 @__int_to_string(i64)
declare i64 @__list_join(i64, i64)
declare i64 @__join_append(i64, i64, i64, i64, i64)
declare i64 @__list_contains(i64, i64)
declare i64 @__io_read_file(i64)
declare i64 @__io_write_file(i64, i64)
declare i64 @__io_file_exists(i64)
declare i64 @__io_mkdir(i64)
declare i64 @__io_walk_dir(i64)
declare i64 @__io_append_file(i64, i64)
declare i64 @__io_file_size(i64)
declare i64 @__io_read_binary(i64, i64, i64)
declare i64 @__io_is_dir(i64)
declare i64 @__io_rename(i64, i64)
declare i64 @__io_delete_file(i64)
declare i64 @__os_set_env(i64, i64)
declare i64 @__os_home()
declare i64 @__io_read_stdin(i64)
declare i64 @__io_readline()
declare i64 @__os_exec(i64)
declare i64 @__os_args()
declare i64 @__os_cwd()
declare i64 @__os_path_sep()
declare i64 @__os_platform()
declare i64 @__os_env(i64)
declare i64 @__os_system(i64)
declare i64 @__str_get(i64, i64)
declare i64 @__io_println(i64)
declare i64 @__io_print(i64)
declare i64 @__any_iter_get(i64, i64)
@__debug_location = external global i8*
declare i64 @__val_nil()
declare i1 @__val_is_int(i64)
declare i1 @__val_is_float(i64)
declare i1 @__val_is_string(i64)
declare i1 @__val_is_bool(i64)
declare i1 @__val_is_nil(i64)
declare i1 @__val_is_list(i64)
declare i1 @__val_is_map(i64)
declare i64 @__val_class_tag(i64)

; --- GC runtime ---
declare void @__gc_enable()
declare void @__gc_disable()
declare void @__gc_collect()
declare void @__gc_set_threshold(i64)
declare i64 @__gc_stat_alloc_count()
declare i64 @__gc_stat_total_bytes()
declare i64 @__gc_stat_collections()
declare i64 @__gc_stat_freed_bytes()
declare i64 @__gc_stat_threshold()
declare void @__gc_debug_stats()
declare i64 @__gc_alloc(i64, i64)
declare i64 @__gc_alloc_zeroed(i64, i64)
declare i64 @__gc_realloc(i64, i64, i64)
declare void @__gc_push_root(i64)
declare void @__gc_pop_roots(i64)
declare i64 @__gc_shadow_stack_depth()
declare i64 @__gc_list_new()
declare void @__gc_list_push(i64, i64)
declare i64 @__gc_map_new()
declare i64 @__gc_stringbuilder_new()
declare i64 @__gc_string_alloc(i64)
declare i64 @__gc_closure_new(i64, i64)
declare i64 @__gc_env_alloc(i64)
declare i64 @__gc_instance_alloc(i64)
declare i64 @__gc_get_type_tag(i64)
declare i8* @__sf_malloc(i64)

; --- Scheduler runtime ---
declare double @sf_time_now()
declare i64 @sf_tcp_poll(i64, i64, i64)
declare void @__sched_coro_resume(i64)
declare i64 @__sched_coro_done(i64)
declare void @__sched_coro_destroy(i64)
declare i64 @__sched_get_yield_reason()
declare i64 @__sched_get_yield_arg()
declare i64 @__sched_get_task_result()
declare void @__sched_reset_yield()
declare void @__sched_store_result(i64, i64)
declare i64 @__sched_get_stored_result(i64)
declare i64 @__sched_has_stored_result(i64)

define i64 @Box__init(i64 %self.arg, i64 %v.arg) {
entry:
  %self = alloca i64
  %v = alloca i64
  store i64 %self.arg, i64* %self
  store i64 %v.arg, i64* %v
  %t1 = load i64, i64* %self
  %t2 = load i64, i64* %v
  %t3 = inttoptr i64 %t1 to %Box*
  %t4 = getelementptr %Box, %Box* %t3, i32 0, i32 0
  store volatile i64 %t2, i64* %t4
  ret i64 0
}

define linkonce_odr i64 @Box() {
entry:
  %t5 = call i64 @__gc_alloc(i64 8, i64 10)
  %t6 = inttoptr i64 %t5 to %Box*
  %t7 = getelementptr %Box, %Box* %t6, i32 0, i32 0
  store i64 0, i64* %t7
  %t8 = ptrtoint %Box* %t6 to i64
  ret i64 %t8
}

define i64 @thru(i64 %a.arg, i64 %b.arg) {
entry:
  %a = alloca i64
  %b = alloca i64
  store i64 %a.arg, i64* %a
  store i64 %b.arg, i64* %b
  %t1 = ptrtoint i64* %a to i64
  call void @__gc_push_root(i64 %t1)
  %t2 = ptrtoint i64* %b to i64
  call void @__gc_push_root(i64 %t2)
  %t3 = load i64, i64* %a
  %t4 = load i64, i64* %b
  %t5 = call i64 @__any_eq(i64 %t3, i64 %t4)
  %t6 = call i64 @__val_tag_bool(i64 %t5)
  call void @__gc_pop_roots(i64 2)
  ret i64 %t6
}

define i64 @__saffron_main() {
entry:
  %m1 = alloca i64
  store i64 0, i64* %m1
  %__map_1 = alloca i64
  store i64 0, i64* %__map_1
  %m2 = alloca i64
  store i64 0, i64* %m2
  %__map_2 = alloca i64
  store i64 0, i64* %__map_2
  %em = alloca i64
  store i64 0, i64* %em
  %t1 = ptrtoint i64* %m1 to i64
  call void @__gc_push_root(i64 %t1)
  %t2 = ptrtoint i64* %__map_1 to i64
  call void @__gc_push_root(i64 %t2)
  %t3 = ptrtoint i64* %m2 to i64
  call void @__gc_push_root(i64 %t3)
  %t4 = ptrtoint i64* %__map_2 to i64
  call void @__gc_push_root(i64 %t4)
  %t5 = ptrtoint i64* %em to i64
  call void @__gc_push_root(i64 %t5)
  %t6 = getelementptr [22 x i8], [22 x i8]* @.str.0, i64 0, i64 0
  %t7 = call i64 @__val_tag_ptr(i8* %t6)
  %t8 = call i64 @__list_new()
  %t9 = add i64 0, 1
  %t10 = call i64 @__val_tag_int(i64 %t9)
  %t11 = call i64 @__list_push(i64 %t8, i64 %t10)
  %t12 = add i64 0, 2
  %t13 = call i64 @__val_tag_int(i64 %t12)
  %t14 = call i64 @__list_push(i64 %t8, i64 %t13)
  %t15 = call i64 @__list_new()
  %t16 = add i64 0, 1
  %t17 = call i64 @__val_tag_int(i64 %t16)
  %t18 = call i64 @__list_push(i64 %t15, i64 %t17)
  %t19 = add i64 0, 2
  %t20 = call i64 @__val_tag_int(i64 %t19)
  %t21 = call i64 @__list_push(i64 %t15, i64 %t20)
  %t22 = call i64 @thru(i64 %t8, i64 %t15)
  %t23 = call i64 @__val_untag_bool(i64 %t22)
  %t24 = call i64 @__bool_to_string(i64 %t23)
  %t25 = call i64 @__rt_tag_ptr(i64 %t24)
  %t26 = call i8* @__val_untag_ptr(i64 %t7)
  %t27 = call i8* @__val_untag_ptr(i64 %t25)
  %t28 = call i64 @strlen(i8* %t26)
  %t29 = call i64 @strlen(i8* %t27)
  %t30 = add i64 %t28, %t29
  %t31 = add i64 %t30, 1
  %t32 = call i8* @__sf_malloc(i64 %t31)
  call i8* @strcpy(i8* %t32, i8* %t26)
  call i8* @strcat(i8* %t32, i8* %t27)
  %t33 = ptrtoint i8* %t32 to i64
  %t34 = call i64 @__string_intern(i64 %t33)
  %t35 = inttoptr i64 %t34 to i8*
  %t36 = call i64 @__val_tag_ptr(i8* %t35)
  %t37 = call i64 @__io_println(i64 %t36)
  %t38 = getelementptr [22 x i8], [22 x i8]* @.str.1, i64 0, i64 0
  %t39 = call i64 @__val_tag_ptr(i8* %t38)
  %t40 = call i64 @__list_new()
  %t41 = add i64 0, 1
  %t42 = call i64 @__val_tag_int(i64 %t41)
  %t43 = call i64 @__list_push(i64 %t40, i64 %t42)
  %t44 = add i64 0, 2
  %t45 = call i64 @__val_tag_int(i64 %t44)
  %t46 = call i64 @__list_push(i64 %t40, i64 %t45)
  %t47 = call i64 @__list_new()
  %t48 = add i64 0, 3
  %t49 = call i64 @__val_tag_int(i64 %t48)
  %t50 = call i64 @__list_push(i64 %t47, i64 %t49)
  %t51 = add i64 0, 4
  %t52 = call i64 @__val_tag_int(i64 %t51)
  %t53 = call i64 @__list_push(i64 %t47, i64 %t52)
  %t54 = call i64 @thru(i64 %t40, i64 %t47)
  %t55 = call i64 @__val_untag_bool(i64 %t54)
  %t56 = call i64 @__bool_to_string(i64 %t55)
  %t57 = call i64 @__rt_tag_ptr(i64 %t56)
  %t58 = call i8* @__val_untag_ptr(i64 %t39)
  %t59 = call i8* @__val_untag_ptr(i64 %t57)
  %t60 = call i64 @strlen(i8* %t58)
  %t61 = call i64 @strlen(i8* %t59)
  %t62 = add i64 %t60, %t61
  %t63 = add i64 %t62, 1
  %t64 = call i8* @__sf_malloc(i64 %t63)
  call i8* @strcpy(i8* %t64, i8* %t58)
  call i8* @strcat(i8* %t64, i8* %t59)
  %t65 = ptrtoint i8* %t64 to i64
  %t66 = call i64 @__string_intern(i64 %t65)
  %t67 = inttoptr i64 %t66 to i8*
  %t68 = call i64 @__val_tag_ptr(i8* %t67)
  %t69 = call i64 @__io_println(i64 %t68)
  %t70 = call i64 @__map_new()
  store i64 %t70, i64* %__map_1
  %t71 = load i64, i64* %__map_1
  %t72 = getelementptr [2 x i8], [2 x i8]* @.str.2, i64 0, i64 0
  %t73 = call i64 @__val_tag_ptr(i8* %t72)
  %t74 = add i64 0, 1
  %t75 = call i64 @__val_tag_int(i64 %t74)
  %t76 = call i64 @__map_set(i64 %t71, i64 %t73, i64 %t75)
  %t77 = load i64, i64* %__map_1
  store i64 %t77, i64* %m1
  %t78 = call i64 @__map_new()
  store i64 %t78, i64* %__map_2
  %t79 = load i64, i64* %__map_2
  %t80 = getelementptr [2 x i8], [2 x i8]* @.str.3, i64 0, i64 0
  %t81 = call i64 @__val_tag_ptr(i8* %t80)
  %t82 = add i64 0, 1
  %t83 = call i64 @__val_tag_int(i64 %t82)
  %t84 = call i64 @__map_set(i64 %t79, i64 %t81, i64 %t83)
  %t85 = load i64, i64* %__map_2
  store i64 %t85, i64* %m2
  %t86 = getelementptr [22 x i8], [22 x i8]* @.str.4, i64 0, i64 0
  %t87 = call i64 @__val_tag_ptr(i8* %t86)
  %t88 = load i64, i64* %m1
  %t89 = load i64, i64* %m2
  %t90 = call i64 @thru(i64 %t88, i64 %t89)
  %t91 = call i64 @__val_untag_bool(i64 %t90)
  %t92 = call i64 @__bool_to_string(i64 %t91)
  %t93 = call i64 @__rt_tag_ptr(i64 %t92)
  %t94 = call i8* @__val_untag_ptr(i64 %t87)
  %t95 = call i8* @__val_untag_ptr(i64 %t93)
  %t96 = call i64 @strlen(i8* %t94)
  %t97 = call i64 @strlen(i8* %t95)
  %t98 = add i64 %t96, %t97
  %t99 = add i64 %t98, 1
  %t100 = call i8* @__sf_malloc(i64 %t99)
  call i8* @strcpy(i8* %t100, i8* %t94)
  call i8* @strcat(i8* %t100, i8* %t95)
  %t101 = ptrtoint i8* %t100 to i64
  %t102 = call i64 @__string_intern(i64 %t101)
  %t103 = inttoptr i64 %t102 to i8*
  %t104 = call i64 @__val_tag_ptr(i8* %t103)
  %t105 = call i64 @__io_println(i64 %t104)
  %t106 = getelementptr [23 x i8], [23 x i8]* @.str.5, i64 0, i64 0
  %t107 = call i64 @__val_tag_ptr(i8* %t106)
  %t108 = call i64 @Box()
  %t109 = add i64 0, 1
  %t110 = call i64 @__val_tag_int(i64 %t109)
  %t111 = call i64 @Box__init(i64 %t108, i64 %t110)
  %t112 = call i64 @Box()
  %t113 = add i64 0, 1
  %t114 = call i64 @__val_tag_int(i64 %t113)
  %t115 = call i64 @Box__init(i64 %t112, i64 %t114)
  %t116 = call i64 @thru(i64 %t108, i64 %t112)
  %t117 = call i64 @__val_untag_bool(i64 %t116)
  %t118 = call i64 @__bool_to_string(i64 %t117)
  %t119 = call i64 @__rt_tag_ptr(i64 %t118)
  %t120 = call i8* @__val_untag_ptr(i64 %t107)
  %t121 = call i8* @__val_untag_ptr(i64 %t119)
  %t122 = call i64 @strlen(i8* %t120)
  %t123 = call i64 @strlen(i8* %t121)
  %t124 = add i64 %t122, %t123
  %t125 = add i64 %t124, 1
  %t126 = call i8* @__sf_malloc(i64 %t125)
  call i8* @strcpy(i8* %t126, i8* %t120)
  call i8* @strcat(i8* %t126, i8* %t121)
  %t127 = ptrtoint i8* %t126 to i64
  %t128 = call i64 @__string_intern(i64 %t127)
  %t129 = inttoptr i64 %t128 to i8*
  %t130 = call i64 @__val_tag_ptr(i8* %t129)
  %t131 = call i64 @__io_println(i64 %t130)
  %t132 = getelementptr [22 x i8], [22 x i8]* @.str.6, i64 0, i64 0
  %t133 = call i64 @__val_tag_ptr(i8* %t132)
  %t134 = call i64 @__list_new()
  %t135 = add i64 0, 1
  %t136 = call i64 @__val_tag_int(i64 %t135)
  %t137 = call i64 @__list_push(i64 %t134, i64 %t136)
  %t138 = add i64 0, 2
  %t139 = call i64 @__val_tag_int(i64 %t138)
  %t140 = call i64 @__list_push(i64 %t134, i64 %t139)
  %t141 = getelementptr [3 x i8], [3 x i8]* @.str.7, i64 0, i64 0
  %t142 = call i64 @__val_tag_ptr(i8* %t141)
  %t143 = call i64 @thru(i64 %t134, i64 %t142)
  %t144 = call i64 @__val_untag_bool(i64 %t143)
  %t145 = call i64 @__bool_to_string(i64 %t144)
  %t146 = call i64 @__rt_tag_ptr(i64 %t145)
  %t147 = call i8* @__val_untag_ptr(i64 %t133)
  %t148 = call i8* @__val_untag_ptr(i64 %t146)
  %t149 = call i64 @strlen(i8* %t147)
  %t150 = call i64 @strlen(i8* %t148)
  %t151 = add i64 %t149, %t150
  %t152 = add i64 %t151, 1
  %t153 = call i8* @__sf_malloc(i64 %t152)
  call i8* @strcpy(i8* %t153, i8* %t147)
  call i8* @strcat(i8* %t153, i8* %t148)
  %t154 = ptrtoint i8* %t153 to i64
  %t155 = call i64 @__string_intern(i64 %t154)
  %t156 = inttoptr i64 %t155 to i8*
  %t157 = call i64 @__val_tag_ptr(i8* %t156)
  %t158 = call i64 @__io_println(i64 %t157)
  %t159 = getelementptr [23 x i8], [23 x i8]* @.str.8, i64 0, i64 0
  %t160 = call i64 @__val_tag_ptr(i8* %t159)
  %t161 = call i64 @__list_new()
  %t162 = call i64 @__list_new()
  %t163 = call i64 @thru(i64 %t161, i64 %t162)
  %t164 = call i64 @__val_untag_bool(i64 %t163)
  %t165 = call i64 @__bool_to_string(i64 %t164)
  %t166 = call i64 @__rt_tag_ptr(i64 %t165)
  %t167 = call i8* @__val_untag_ptr(i64 %t160)
  %t168 = call i8* @__val_untag_ptr(i64 %t166)
  %t169 = call i64 @strlen(i8* %t167)
  %t170 = call i64 @strlen(i8* %t168)
  %t171 = add i64 %t169, %t170
  %t172 = add i64 %t171, 1
  %t173 = call i8* @__sf_malloc(i64 %t172)
  call i8* @strcpy(i8* %t173, i8* %t167)
  call i8* @strcat(i8* %t173, i8* %t168)
  %t174 = ptrtoint i8* %t173 to i64
  %t175 = call i64 @__string_intern(i64 %t174)
  %t176 = inttoptr i64 %t175 to i8*
  %t177 = call i64 @__val_tag_ptr(i8* %t176)
  %t178 = call i64 @__io_println(i64 %t177)
  %t179 = getelementptr [22 x i8], [22 x i8]* @.str.9, i64 0, i64 0
  %t180 = call i64 @__val_tag_ptr(i8* %t179)
  %t181 = call i64 @__list_new()
  %t182 = getelementptr [1 x i8], [1 x i8]* @.str.10, i64 0, i64 0
  %t183 = call i64 @__val_tag_ptr(i8* %t182)
  %t184 = call i64 @thru(i64 %t181, i64 %t183)
  %t185 = call i64 @__val_untag_bool(i64 %t184)
  %t186 = call i64 @__bool_to_string(i64 %t185)
  %t187 = call i64 @__rt_tag_ptr(i64 %t186)
  %t188 = call i8* @__val_untag_ptr(i64 %t180)
  %t189 = call i8* @__val_untag_ptr(i64 %t187)
  %t190 = call i64 @strlen(i8* %t188)
  %t191 = call i64 @strlen(i8* %t189)
  %t192 = add i64 %t190, %t191
  %t193 = add i64 %t192, 1
  %t194 = call i8* @__sf_malloc(i64 %t193)
  call i8* @strcpy(i8* %t194, i8* %t188)
  call i8* @strcat(i8* %t194, i8* %t189)
  %t195 = ptrtoint i8* %t194 to i64
  %t196 = call i64 @__string_intern(i64 %t195)
  %t197 = inttoptr i64 %t196 to i8*
  %t198 = call i64 @__val_tag_ptr(i8* %t197)
  %t199 = call i64 @__io_println(i64 %t198)
  %t200 = call i64 @__map_new()
  store i64 %t200, i64* %em
  %t201 = getelementptr [23 x i8], [23 x i8]* @.str.11, i64 0, i64 0
  %t202 = call i64 @__val_tag_ptr(i8* %t201)
  %t203 = load i64, i64* %em
  %t204 = call i64 @__list_new()
  %t205 = call i64 @thru(i64 %t203, i64 %t204)
  %t206 = call i64 @__val_untag_bool(i64 %t205)
  %t207 = call i64 @__bool_to_string(i64 %t206)
  %t208 = call i64 @__rt_tag_ptr(i64 %t207)
  %t209 = call i8* @__val_untag_ptr(i64 %t202)
  %t210 = call i8* @__val_untag_ptr(i64 %t208)
  %t211 = call i64 @strlen(i8* %t209)
  %t212 = call i64 @strlen(i8* %t210)
  %t213 = add i64 %t211, %t212
  %t214 = add i64 %t213, 1
  %t215 = call i8* @__sf_malloc(i64 %t214)
  call i8* @strcpy(i8* %t215, i8* %t209)
  call i8* @strcat(i8* %t215, i8* %t210)
  %t216 = ptrtoint i8* %t215 to i64
  %t217 = call i64 @__string_intern(i64 %t216)
  %t218 = inttoptr i64 %t217 to i8*
  %t219 = call i64 @__val_tag_ptr(i8* %t218)
  %t220 = call i64 @__io_println(i64 %t219)
  call void @__gc_pop_roots(i64 5)
  ret i64 0
}

define i64 @__reflect_class_name(i64 %val) {
entry:
  %t1 = call i64 @__gc_get_type_tag(i64 %val)
  switch i64 %t1, label %rcn.end1 [ i64 10, label %rcn.c2 ]
rcn.c2:
  %t2 = getelementptr [4 x i8], [4 x i8]* @.str.12, i64 0, i64 0
  %t3 = ptrtoint i8* %t2 to i64
  ret i64 %t3
rcn.end1:
  %t4 = getelementptr [8 x i8], [8 x i8]* @.str.13, i64 0, i64 0
  %t5 = ptrtoint i8* %t4 to i64
  ret i64 %t5
}

define i64 @__reflect_is_class(i64 %val) {
entry:
  %t1 = call i64 @__gc_get_type_tag(i64 %val)
  %t2 = icmp uge i64 %t1, 10
  %t3 = zext i1 %t2 to i64
  ret i64 %t3
}

define i64 @__reflect_number_to_string(i64 %val) {
entry:
  %t1 = call i64 @__val_untag_int(i64 %val)
  %t2 = call i64 @__int_to_string(i64 %t1)
  %t3 = inttoptr i64 %t2 to i8*
  %t4 = call i64 @__val_tag_ptr(i8* %t3)
  ret i64 %t4
}

define i64 @__reflect_get_fields(i64 %val) {
entry:
  %t1 = call i64 @__gc_get_type_tag(i64 %val)
  switch i64 %t1, label %rgf.end3 [ i64 10, label %rgf.c4 ]
rgf.c4:
  %t2 = call i64 @__map_new()
  %t3 = getelementptr [2 x i8], [2 x i8]* @.str.14, i64 0, i64 0
  %t4 = call i64 @__val_tag_ptr(i8* %t3)
  %t5 = inttoptr i64 %val to %Box*
  %t6 = getelementptr %Box, %Box* %t5, i32 0, i32 0
  %t7 = load i64, i64* %t6
  call i64 @__map_set(i64 %t2, i64 %t4, i64 %t7)
  ret i64 %t2
rgf.end3:
  %t8 = call i64 @__map_new()
  ret i64 %t8
}

define i64 @__reflect_construct_from_map(i64 %klass, i64 %map) {
entry:
  %t1 = ptrtoint i64 (...)* bitcast (i64 ()* @Box to i64 (...)*) to i64
  %t2 = icmp eq i64 %klass, %t1
  br i1 %t2, label %rcon.hit6, label %rcon.end5
rcon.hit6:
  %t3 = call i64 @Box()
  %t4 = inttoptr i64 %t3 to %Box*
  %t5 = getelementptr [2 x i8], [2 x i8]* @.str.15, i64 0, i64 0
  %t6 = ptrtoint i8* %t5 to i64
  %t7 = call i64 @__map_get(i64 %map, i64 %t6)
  %t8 = getelementptr %Box, %Box* %t4, i32 0, i32 0
  store i64 %t7, i64* %t8
  ret i64 %t3
rcon.end5:
  ret i64 0
}

define i64 @__class_parent_tag(i64 %tag) {
entry:
  ret i64 0
}

define i1 @__class_is_a(i64 %tag, i64 %target) {
entry:
  %z = icmp eq i64 %tag, 0
  br i1 %z, label %cia.no, label %cia.tchk
cia.tchk:
  %tz = icmp eq i64 %target, 0
  br i1 %tz, label %cia.no, label %cia.self
cia.self:
  %hit = icmp eq i64 %tag, %target
  br i1 %hit, label %cia.yes, label %cia.no
cia.yes:
  ret i1 1
cia.no:
  ret i1 0
}

define i64 @__saffron_entry() {
entry:
  call void @__gc_enable()
  %t1 = call i64 @__saffron_main()
  ret i64 0
}

define i32 @main(i32 %argc, i8** %argv) {
entry:
  store i32 %argc, i32* @__argc
  store i8** %argv, i8*** @__argv
  call i64 @__saffron_entry()
  ret i32 0
}
