; Generated by Saffron LLVM compiler
target triple = "arm64-apple-macosx15.0.0"

@.str.0 = private unnamed_addr constant [4 x i8] c"Red\00"
@.str.1 = private unnamed_addr constant [6 x i8] c"Green\00"
@.str.2 = private unnamed_addr constant [5 x i8] c"Blue\00"
@.str.3 = private unnamed_addr constant [8 x i8] c"Unknown\00"
@.str.4 = private unnamed_addr constant [8 x i8] c"Circle(\00"
@.str.5 = private unnamed_addr constant [2 x i8] c")\00"
@.str.6 = private unnamed_addr constant [8 x i8] c"Square(\00"
@.str.7 = private unnamed_addr constant [2 x i8] c")\00"
@.str.8 = private unnamed_addr constant [7 x i8] c"Group(\00"
@.str.9 = private unnamed_addr constant [2 x i8] c")\00"
@.str.10 = private unnamed_addr constant [8 x i8] c"Unknown\00"
@.str.11 = private unnamed_addr constant [29 x i8] c"fieldless eq (want true):   \00"
@.str.12 = private unnamed_addr constant [29 x i8] c"fieldless ne (want false):  \00"
@.str.13 = private unnamed_addr constant [29 x i8] c"payload eq (want true):     \00"
@.str.14 = private unnamed_addr constant [29 x i8] c"payload ne (want false):    \00"
@.str.15 = private unnamed_addr constant [29 x i8] c"cross-variant (want false): \00"
@.str.16 = private unnamed_addr constant [29 x i8] c"nested eq (want true):      \00"

%Color = type { i8, [16 x i8] }
%Shape = type { i8, [16 x i8] }

declare i32 @puts(i8*)
declare i32 @printf(i8*, ...)
declare i32 @snprintf(i8*, i64, i8*, ...)
declare i8* @malloc(i64)
declare i8* @realloc(i8*, i64)
declare void @free(i8*)
declare i64 @strlen(i8*)
declare i8* @strcpy(i8*, i8*)
declare i8* @strcat(i8*, i8*)
declare i8* @strstr(i8*, i8*)
declare i32 @strcmp(i8*, i8*)
declare i32 @strncmp(i8*, i8*, i64)
declare i64 @atol(i8*)
declare void @exit(i32)
declare i8* @fopen(i8*, i8*)
declare i64 @fread(i8*, i64, i64, i8*)
declare i64 @fwrite(i8*, i64, i64, i8*)
declare i32 @fclose(i8*)
declare i32 @fseek(i8*, i64, i32)
declare i64 @ftell(i8*)
declare i8* @strtok(i8*, i8*)
declare i32 @pclose(i8*)
declare i8* @popen(i8*, i8*)
declare i8* @fgets(i8*, i32, i8*)
declare void @llvm.memcpy.p0i8.p0i8.i64(i8*, i8*, i64, i1)
declare i32 @setjmp(i8*) returns_twice
declare void @longjmp(i8*, i32) noreturn
declare void @__io_println_str(i64)
declare void @__io_println_int(i64)
declare void @__io_println_bool(i64)
declare void @__io_println_nil()
declare void @__io_println_any(i64)
declare void @__io_print_str(i64)
declare void @__io_print_int(i64)
declare i64 @__any_to_string(i64)
declare i64 @__bool_to_string(i64)
declare i64 @__nil_to_string()

declare i64 @__float_to_string(i64)
declare i64 @__string_eq(i64, i64)
declare i64 @__string_ne(i64, i64)
declare i64 @__any_eq(i64, i64)
declare i64 @__any_ne(i64, i64)
declare i64 @__string_intern(i64)
; --- NaN-boxing value helpers ---
declare i64 @__val_tag_int(i64)
declare i64 @__val_untag_int(i64)
declare i64 @__val_tag_ptr(i8*)
declare i64 @__val_tag_ptr_nullable(i8*)
declare i8* @__val_untag_ptr(i64)
declare i64 @__val_tag_float(double)
declare double @__val_untag_float(i64)
declare i64 @__val_tag_bool(i64)
declare i64 @__val_untag_bool(i64)
declare i64 @__rt_tag_ptr(i64)
declare double @strtod(i8*, i8*)
declare double @llvm.floor.f64(double)

declare i64 @__division_error()
declare i64 @__null_pointer_error()
declare i64 @__runtime_error(i64)
declare i64 @__runtime_error_fatal(i64)

@.fmt.ld = linkonce_odr unnamed_addr constant [4 x i8] c"%ld\00"
@.str.empty = linkonce_odr unnamed_addr constant [1 x i8] c"\00"
@.str.rb = linkonce_odr unnamed_addr constant [2 x i8] c"r\00"
@.str.wb = linkonce_odr unnamed_addr constant [2 x i8] c"w\00"
@.str.r = linkonce_odr unnamed_addr constant [2 x i8] c"r\00"
@__argc = weak global i32 0
@__argv = weak global i8** null
@__exception_value = weak global i64 0
@__jmp_buf_current = weak global i8* null

; List = { count, capacity, data* }
%List = type { i64, i64, i64* }
; Map = { count, capacity, keys*, values* }
%Map = type { i64, i64, i64*, i64* }

; --- Runtime declarations ---
%SB = type { i64, i64, i8* }

declare i64 @__list_new()
declare i64 @__list_push(i64, i64)
declare i64 @__list_get(i64, i64)
declare i64 @__list_set(i64, i64, i64)
declare i64 @__list_length(i64)
declare i64 @__list_pop(i64)
declare i64 @__list_remove(i64, i64)
declare i64 @__list_slice(i64, i64, i64)
declare i64 @StringBuilder()
declare i64 @__sb_append(i64, i64)
declare i64 @__sb_to_string(i64)
declare i64 @__safe_strcmp(i64, i64)
declare i64 @__map_new()
declare i64 @__map_set(i64, i64, i64)
declare i64 @__map_get(i64, i64)
declare i64 @__map_has(i64, i64)
declare i64 @__map_keys(i64)
declare i64 @__str_ends_with(i64, i64)
declare i64 @__str_split(i64, i64)
declare i64 @__str_replace(i64, i64, i64)
declare i64 @__int_to_string(i64)
declare i64 @__list_join(i64, i64)
declare i64 @__join_append(i64, i64, i64, i64, i64)
declare i64 @__list_contains(i64, i64)
declare i64 @__io_read_file(i64)
declare i64 @__io_write_file(i64, i64)
declare i64 @__io_file_exists(i64)
declare i64 @__io_mkdir(i64)
declare i64 @__io_walk_dir(i64)
declare i64 @__io_append_file(i64, i64)
declare i64 @__io_file_size(i64)
declare i64 @__io_read_binary(i64, i64, i64)
declare i64 @__io_is_dir(i64)
declare i64 @__io_rename(i64, i64)
declare i64 @__io_delete_file(i64)
declare i64 @__os_set_env(i64, i64)
declare i64 @__os_home()
declare i64 @__io_read_stdin(i64)
declare i64 @__io_readline()
declare i64 @__os_exec(i64)
declare i64 @__os_args()
declare i64 @__os_cwd()
declare i64 @__os_path_sep()
declare i64 @__os_platform()
declare i64 @__os_env(i64)
declare i64 @__os_system(i64)
declare i64 @__str_get(i64, i64)
declare i64 @__io_println(i64)
declare i64 @__io_print(i64)
declare i64 @__any_iter_get(i64, i64)
@__debug_location = external global i8*
declare i64 @__val_nil()
declare i1 @__val_is_int(i64)
declare i1 @__val_is_float(i64)
declare i1 @__val_is_string(i64)
declare i1 @__val_is_bool(i64)
declare i1 @__val_is_nil(i64)
declare i1 @__val_is_list(i64)
declare i1 @__val_is_map(i64)
declare i64 @__val_class_tag(i64)

; --- GC runtime ---
declare void @__gc_enable()
declare void @__gc_disable()
declare void @__gc_collect()
declare void @__gc_set_threshold(i64)
declare i64 @__gc_stat_alloc_count()
declare i64 @__gc_stat_total_bytes()
declare i64 @__gc_stat_collections()
declare i64 @__gc_stat_freed_bytes()
declare i64 @__gc_stat_threshold()
declare void @__gc_debug_stats()
declare i64 @__gc_alloc(i64, i64)
declare i64 @__gc_alloc_zeroed(i64, i64)
declare i64 @__gc_realloc(i64, i64, i64)
declare void @__gc_push_root(i64)
declare void @__gc_pop_roots(i64)
declare i64 @__gc_shadow_stack_depth()
declare i64 @__gc_list_new()
declare void @__gc_list_push(i64, i64)
declare i64 @__gc_map_new()
declare i64 @__gc_stringbuilder_new()
declare i64 @__gc_string_alloc(i64)
declare i64 @__gc_closure_new(i64, i64)
declare i64 @__gc_env_alloc(i64)
declare i64 @__gc_instance_alloc(i64)
declare i64 @__gc_get_type_tag(i64)
declare i8* @__sf_malloc(i64)

; --- Scheduler runtime ---
declare double @sf_time_now()
declare i64 @sf_tcp_poll(i64, i64, i64)
declare void @__sched_coro_resume(i64)
declare i64 @__sched_coro_done(i64)
declare void @__sched_coro_destroy(i64)
declare i64 @__sched_get_yield_reason()
declare i64 @__sched_get_yield_arg()
declare i64 @__sched_get_task_result()
declare void @__sched_reset_yield()
declare void @__sched_store_result(i64, i64)
declare i64 @__sched_get_stored_result(i64)
declare i64 @__sched_has_stored_result(i64)

define linkonce_odr i64 @Color__to_string(i64 %self) {
entry:
  %t1 = lshr i64 %self, 56
  switch i64 %t1, label %ets.end1 [ i64 0, label %ets.v2 i64 1, label %ets.v3 i64 2, label %ets.v4 ]
ets.v2:
  %t2 = getelementptr [4 x i8], [4 x i8]* @.str.0, i64 0, i64 0
  %t3 = ptrtoint i8* %t2 to i64
  ret i64 %t3
ets.v3:
  %t4 = getelementptr [6 x i8], [6 x i8]* @.str.1, i64 0, i64 0
  %t5 = ptrtoint i8* %t4 to i64
  ret i64 %t5
ets.v4:
  %t6 = getelementptr [5 x i8], [5 x i8]* @.str.2, i64 0, i64 0
  %t7 = ptrtoint i8* %t6 to i64
  ret i64 %t7
ets.end1:
  %t8 = getelementptr [8 x i8], [8 x i8]* @.str.3, i64 0, i64 0
  %t9 = ptrtoint i8* %t8 to i64
  ret i64 %t9
}

define linkonce_odr i64 @Circle(i64 %f0) {
entry:
  %t1 = call i8* @__sf_malloc(i64 16)
  %t2 = bitcast i8* %t1 to [2 x i64]*
  %t3 = getelementptr [2 x i64], [2 x i64]* %t2, i64 0, i64 0
  store i64 0, i64* %t3
  %t4 = getelementptr [2 x i64], [2 x i64]* %t2, i64 0, i64 1
  store i64 %f0, i64* %t4
  %t5 = ptrtoint [2 x i64]* %t2 to i64
  ret i64 %t5
}

define linkonce_odr i64 @Square(i64 %f0) {
entry:
  %t1 = call i8* @__sf_malloc(i64 16)
  %t2 = bitcast i8* %t1 to [2 x i64]*
  %t3 = getelementptr [2 x i64], [2 x i64]* %t2, i64 0, i64 0
  store i64 1, i64* %t3
  %t4 = getelementptr [2 x i64], [2 x i64]* %t2, i64 0, i64 1
  store i64 %f0, i64* %t4
  %t5 = ptrtoint [2 x i64]* %t2 to i64
  ret i64 %t5
}

define linkonce_odr i64 @Group(i64 %f0) {
entry:
  %t1 = call i8* @__sf_malloc(i64 16)
  %t2 = bitcast i8* %t1 to [2 x i64]*
  %t3 = getelementptr [2 x i64], [2 x i64]* %t2, i64 0, i64 0
  store i64 2, i64* %t3
  %t4 = getelementptr [2 x i64], [2 x i64]* %t2, i64 0, i64 1
  store i64 %f0, i64* %t4
  %t5 = ptrtoint [2 x i64]* %t2 to i64
  ret i64 %t5
}

define linkonce_odr i64 @Shape__to_string(i64 %self) {
entry:
  %t1 = inttoptr i64 %self to i64*
  %t2 = load i64, i64* %t1
  switch i64 %t2, label %ets.end5 [ i64 0, label %ets.v6 i64 1, label %ets.v7 i64 2, label %ets.v8 ]
ets.v6:
  %t3 = getelementptr [8 x i8], [8 x i8]* @.str.4, i64 0, i64 0
  %t4 = ptrtoint i8* %t3 to i64
  %t5 = call i64 @StringBuilder()
  call i64 @__sb_append(i64 %t5, i64 %t4)
  %t6 = inttoptr i64 %self to [2 x i64]*
  %t7 = getelementptr [2 x i64], [2 x i64]* %t6, i64 0, i64 1
  %t8 = load i64, i64* %t7
  %t9 = call i64 @__float_to_string(i64 %t8)
  call i64 @__sb_append(i64 %t5, i64 %t9)
  %t10 = getelementptr [2 x i8], [2 x i8]* @.str.5, i64 0, i64 0
  %t11 = ptrtoint i8* %t10 to i64
  call i64 @__sb_append(i64 %t5, i64 %t11)
  %t12 = call i64 @__sb_to_string(i64 %t5)
  ret i64 %t12
ets.v7:
  %t13 = getelementptr [8 x i8], [8 x i8]* @.str.6, i64 0, i64 0
  %t14 = ptrtoint i8* %t13 to i64
  %t15 = call i64 @StringBuilder()
  call i64 @__sb_append(i64 %t15, i64 %t14)
  %t16 = inttoptr i64 %self to [2 x i64]*
  %t17 = getelementptr [2 x i64], [2 x i64]* %t16, i64 0, i64 1
  %t18 = load i64, i64* %t17
  %t19 = call i64 @__float_to_string(i64 %t18)
  call i64 @__sb_append(i64 %t15, i64 %t19)
  %t20 = getelementptr [2 x i8], [2 x i8]* @.str.7, i64 0, i64 0
  %t21 = ptrtoint i8* %t20 to i64
  call i64 @__sb_append(i64 %t15, i64 %t21)
  %t22 = call i64 @__sb_to_string(i64 %t15)
  ret i64 %t22
ets.v8:
  %t23 = getelementptr [7 x i8], [7 x i8]* @.str.8, i64 0, i64 0
  %t24 = ptrtoint i8* %t23 to i64
  %t25 = call i64 @StringBuilder()
  call i64 @__sb_append(i64 %t25, i64 %t24)
  %t26 = inttoptr i64 %self to [2 x i64]*
  %t27 = getelementptr [2 x i64], [2 x i64]* %t26, i64 0, i64 1
  %t28 = load i64, i64* %t27
  %t29 = call i64 @Shape__to_string(i64 %t28)
  call i64 @__sb_append(i64 %t25, i64 %t29)
  %t30 = getelementptr [2 x i8], [2 x i8]* @.str.9, i64 0, i64 0
  %t31 = ptrtoint i8* %t30 to i64
  call i64 @__sb_append(i64 %t25, i64 %t31)
  %t32 = call i64 @__sb_to_string(i64 %t25)
  ret i64 %t32
ets.end5:
  %t33 = getelementptr [8 x i8], [8 x i8]* @.str.10, i64 0, i64 0
  %t34 = ptrtoint i8* %t33 to i64
  ret i64 %t34
}

define i64 @__saffron_main() {
entry:
  %a = alloca i64
  store i64 0, i64* %a
  %b = alloca i64
  store i64 0, i64* %b
  %t1 = ptrtoint i64* %a to i64
  call void @__gc_push_root(i64 %t1)
  %t2 = ptrtoint i64* %b to i64
  call void @__gc_push_root(i64 %t2)
  %t3 = getelementptr [29 x i8], [29 x i8]* @.str.11, i64 0, i64 0
  %t4 = call i64 @__val_tag_ptr(i8* %t3)
  %t5 = shl i64 0, 56
  %t6 = shl i64 0, 56
  %t7 = icmp eq i64 %t5, %t6
  %t8 = zext i1 %t7 to i64
  %t9 = call i64 @__val_tag_bool(i64 %t8)
  %t10 = call i64 @__val_untag_bool(i64 %t9)
  %t11 = call i64 @__bool_to_string(i64 %t10)
  %t12 = call i64 @__rt_tag_ptr(i64 %t11)
  %t13 = call i8* @__val_untag_ptr(i64 %t4)
  %t14 = call i8* @__val_untag_ptr(i64 %t12)
  %t15 = call i64 @strlen(i8* %t13)
  %t16 = call i64 @strlen(i8* %t14)
  %t17 = add i64 %t15, %t16
  %t18 = add i64 %t17, 1
  %t19 = call i8* @__sf_malloc(i64 %t18)
  call i8* @strcpy(i8* %t19, i8* %t13)
  call i8* @strcat(i8* %t19, i8* %t14)
  %t20 = ptrtoint i8* %t19 to i64
  %t21 = call i64 @__string_intern(i64 %t20)
  %t22 = inttoptr i64 %t21 to i8*
  %t23 = call i64 @__val_tag_ptr(i8* %t22)
  %t24 = call i64 @__io_println(i64 %t23)
  %t25 = getelementptr [29 x i8], [29 x i8]* @.str.12, i64 0, i64 0
  %t26 = call i64 @__val_tag_ptr(i8* %t25)
  %t27 = shl i64 0, 56
  %t28 = shl i64 1, 56
  %t29 = icmp eq i64 %t27, %t28
  %t30 = zext i1 %t29 to i64
  %t31 = call i64 @__val_tag_bool(i64 %t30)
  %t32 = call i64 @__val_untag_bool(i64 %t31)
  %t33 = call i64 @__bool_to_string(i64 %t32)
  %t34 = call i64 @__rt_tag_ptr(i64 %t33)
  %t35 = call i8* @__val_untag_ptr(i64 %t26)
  %t36 = call i8* @__val_untag_ptr(i64 %t34)
  %t37 = call i64 @strlen(i8* %t35)
  %t38 = call i64 @strlen(i8* %t36)
  %t39 = add i64 %t37, %t38
  %t40 = add i64 %t39, 1
  %t41 = call i8* @__sf_malloc(i64 %t40)
  call i8* @strcpy(i8* %t41, i8* %t35)
  call i8* @strcat(i8* %t41, i8* %t36)
  %t42 = ptrtoint i8* %t41 to i64
  %t43 = call i64 @__string_intern(i64 %t42)
  %t44 = inttoptr i64 %t43 to i8*
  %t45 = call i64 @__val_tag_ptr(i8* %t44)
  %t46 = call i64 @__io_println(i64 %t45)
  %t47 = getelementptr [29 x i8], [29 x i8]* @.str.13, i64 0, i64 0
  %t48 = call i64 @__val_tag_ptr(i8* %t47)
  %t49 = call i8* @__sf_malloc(i64 16)
  %t50 = bitcast i8* %t49 to [2 x i64]*
  %t51 = getelementptr [2 x i64], [2 x i64]* %t50, i64 0, i64 0
  store i64 0, i64* %t51
  %t52 = add i64 0, 2
  %t53 = call i64 @__val_tag_int(i64 %t52)
  %t54 = call double @__val_untag_float(i64 %t53)
  %t55 = call i64 @__val_tag_float(double %t54)
  %t56 = getelementptr [2 x i64], [2 x i64]* %t50, i64 0, i64 1
  store i64 %t55, i64* %t56
  %t57 = ptrtoint [2 x i64]* %t50 to i64
  %t58 = call i8* @__sf_malloc(i64 16)
  %t59 = bitcast i8* %t58 to [2 x i64]*
  %t60 = getelementptr [2 x i64], [2 x i64]* %t59, i64 0, i64 0
  store i64 0, i64* %t60
  %t61 = add i64 0, 2
  %t62 = call i64 @__val_tag_int(i64 %t61)
  %t63 = call double @__val_untag_float(i64 %t62)
  %t64 = call i64 @__val_tag_float(double %t63)
  %t65 = getelementptr [2 x i64], [2 x i64]* %t59, i64 0, i64 1
  store i64 %t64, i64* %t65
  %t66 = ptrtoint [2 x i64]* %t59 to i64
  %t67 = icmp eq i64 %t57, %t66
  %t68 = zext i1 %t67 to i64
  %t69 = call i64 @__val_tag_bool(i64 %t68)
  %t70 = call i64 @__val_untag_bool(i64 %t69)
  %t71 = call i64 @__bool_to_string(i64 %t70)
  %t72 = call i64 @__rt_tag_ptr(i64 %t71)
  %t73 = call i8* @__val_untag_ptr(i64 %t48)
  %t74 = call i8* @__val_untag_ptr(i64 %t72)
  %t75 = call i64 @strlen(i8* %t73)
  %t76 = call i64 @strlen(i8* %t74)
  %t77 = add i64 %t75, %t76
  %t78 = add i64 %t77, 1
  %t79 = call i8* @__sf_malloc(i64 %t78)
  call i8* @strcpy(i8* %t79, i8* %t73)
  call i8* @strcat(i8* %t79, i8* %t74)
  %t80 = ptrtoint i8* %t79 to i64
  %t81 = call i64 @__string_intern(i64 %t80)
  %t82 = inttoptr i64 %t81 to i8*
  %t83 = call i64 @__val_tag_ptr(i8* %t82)
  %t84 = call i64 @__io_println(i64 %t83)
  %t85 = getelementptr [29 x i8], [29 x i8]* @.str.14, i64 0, i64 0
  %t86 = call i64 @__val_tag_ptr(i8* %t85)
  %t87 = call i8* @__sf_malloc(i64 16)
  %t88 = bitcast i8* %t87 to [2 x i64]*
  %t89 = getelementptr [2 x i64], [2 x i64]* %t88, i64 0, i64 0
  store i64 0, i64* %t89
  %t90 = add i64 0, 2
  %t91 = call i64 @__val_tag_int(i64 %t90)
  %t92 = call double @__val_untag_float(i64 %t91)
  %t93 = call i64 @__val_tag_float(double %t92)
  %t94 = getelementptr [2 x i64], [2 x i64]* %t88, i64 0, i64 1
  store i64 %t93, i64* %t94
  %t95 = ptrtoint [2 x i64]* %t88 to i64
  %t96 = call i8* @__sf_malloc(i64 16)
  %t97 = bitcast i8* %t96 to [2 x i64]*
  %t98 = getelementptr [2 x i64], [2 x i64]* %t97, i64 0, i64 0
  store i64 0, i64* %t98
  %t99 = add i64 0, 3
  %t100 = call i64 @__val_tag_int(i64 %t99)
  %t101 = call double @__val_untag_float(i64 %t100)
  %t102 = call i64 @__val_tag_float(double %t101)
  %t103 = getelementptr [2 x i64], [2 x i64]* %t97, i64 0, i64 1
  store i64 %t102, i64* %t103
  %t104 = ptrtoint [2 x i64]* %t97 to i64
  %t105 = icmp eq i64 %t95, %t104
  %t106 = zext i1 %t105 to i64
  %t107 = call i64 @__val_tag_bool(i64 %t106)
  %t108 = call i64 @__val_untag_bool(i64 %t107)
  %t109 = call i64 @__bool_to_string(i64 %t108)
  %t110 = call i64 @__rt_tag_ptr(i64 %t109)
  %t111 = call i8* @__val_untag_ptr(i64 %t86)
  %t112 = call i8* @__val_untag_ptr(i64 %t110)
  %t113 = call i64 @strlen(i8* %t111)
  %t114 = call i64 @strlen(i8* %t112)
  %t115 = add i64 %t113, %t114
  %t116 = add i64 %t115, 1
  %t117 = call i8* @__sf_malloc(i64 %t116)
  call i8* @strcpy(i8* %t117, i8* %t111)
  call i8* @strcat(i8* %t117, i8* %t112)
  %t118 = ptrtoint i8* %t117 to i64
  %t119 = call i64 @__string_intern(i64 %t118)
  %t120 = inttoptr i64 %t119 to i8*
  %t121 = call i64 @__val_tag_ptr(i8* %t120)
  %t122 = call i64 @__io_println(i64 %t121)
  %t123 = getelementptr [29 x i8], [29 x i8]* @.str.15, i64 0, i64 0
  %t124 = call i64 @__val_tag_ptr(i8* %t123)
  %t125 = call i8* @__sf_malloc(i64 16)
  %t126 = bitcast i8* %t125 to [2 x i64]*
  %t127 = getelementptr [2 x i64], [2 x i64]* %t126, i64 0, i64 0
  store i64 0, i64* %t127
  %t128 = add i64 0, 2
  %t129 = call i64 @__val_tag_int(i64 %t128)
  %t130 = call double @__val_untag_float(i64 %t129)
  %t131 = call i64 @__val_tag_float(double %t130)
  %t132 = getelementptr [2 x i64], [2 x i64]* %t126, i64 0, i64 1
  store i64 %t131, i64* %t132
  %t133 = ptrtoint [2 x i64]* %t126 to i64
  %t134 = call i8* @__sf_malloc(i64 16)
  %t135 = bitcast i8* %t134 to [2 x i64]*
  %t136 = getelementptr [2 x i64], [2 x i64]* %t135, i64 0, i64 0
  store i64 1, i64* %t136
  %t137 = add i64 0, 2
  %t138 = call i64 @__val_tag_int(i64 %t137)
  %t139 = call double @__val_untag_float(i64 %t138)
  %t140 = call i64 @__val_tag_float(double %t139)
  %t141 = getelementptr [2 x i64], [2 x i64]* %t135, i64 0, i64 1
  store i64 %t140, i64* %t141
  %t142 = ptrtoint [2 x i64]* %t135 to i64
  %t143 = icmp eq i64 %t133, %t142
  %t144 = zext i1 %t143 to i64
  %t145 = call i64 @__val_tag_bool(i64 %t144)
  %t146 = call i64 @__val_untag_bool(i64 %t145)
  %t147 = call i64 @__bool_to_string(i64 %t146)
  %t148 = call i64 @__rt_tag_ptr(i64 %t147)
  %t149 = call i8* @__val_untag_ptr(i64 %t124)
  %t150 = call i8* @__val_untag_ptr(i64 %t148)
  %t151 = call i64 @strlen(i8* %t149)
  %t152 = call i64 @strlen(i8* %t150)
  %t153 = add i64 %t151, %t152
  %t154 = add i64 %t153, 1
  %t155 = call i8* @__sf_malloc(i64 %t154)
  call i8* @strcpy(i8* %t155, i8* %t149)
  call i8* @strcat(i8* %t155, i8* %t150)
  %t156 = ptrtoint i8* %t155 to i64
  %t157 = call i64 @__string_intern(i64 %t156)
  %t158 = inttoptr i64 %t157 to i8*
  %t159 = call i64 @__val_tag_ptr(i8* %t158)
  %t160 = call i64 @__io_println(i64 %t159)
  %t161 = call i8* @__sf_malloc(i64 16)
  %t162 = bitcast i8* %t161 to [2 x i64]*
  %t163 = getelementptr [2 x i64], [2 x i64]* %t162, i64 0, i64 0
  store i64 2, i64* %t163
  %t164 = call i8* @__sf_malloc(i64 16)
  %t165 = bitcast i8* %t164 to [2 x i64]*
  %t166 = getelementptr [2 x i64], [2 x i64]* %t165, i64 0, i64 0
  store i64 0, i64* %t166
  %t167 = add i64 0, 2
  %t168 = call i64 @__val_tag_int(i64 %t167)
  %t169 = call double @__val_untag_float(i64 %t168)
  %t170 = call i64 @__val_tag_float(double %t169)
  %t171 = getelementptr [2 x i64], [2 x i64]* %t165, i64 0, i64 1
  store i64 %t170, i64* %t171
  %t172 = ptrtoint [2 x i64]* %t165 to i64
  %t173 = getelementptr [2 x i64], [2 x i64]* %t162, i64 0, i64 1
  store i64 %t172, i64* %t173
  %t174 = ptrtoint [2 x i64]* %t162 to i64
  store i64 %t174, i64* %a
  %t175 = call i8* @__sf_malloc(i64 16)
  %t176 = bitcast i8* %t175 to [2 x i64]*
  %t177 = getelementptr [2 x i64], [2 x i64]* %t176, i64 0, i64 0
  store i64 2, i64* %t177
  %t178 = call i8* @__sf_malloc(i64 16)
  %t179 = bitcast i8* %t178 to [2 x i64]*
  %t180 = getelementptr [2 x i64], [2 x i64]* %t179, i64 0, i64 0
  store i64 0, i64* %t180
  %t181 = add i64 0, 2
  %t182 = call i64 @__val_tag_int(i64 %t181)
  %t183 = call double @__val_untag_float(i64 %t182)
  %t184 = call i64 @__val_tag_float(double %t183)
  %t185 = getelementptr [2 x i64], [2 x i64]* %t179, i64 0, i64 1
  store i64 %t184, i64* %t185
  %t186 = ptrtoint [2 x i64]* %t179 to i64
  %t187 = getelementptr [2 x i64], [2 x i64]* %t176, i64 0, i64 1
  store i64 %t186, i64* %t187
  %t188 = ptrtoint [2 x i64]* %t176 to i64
  store i64 %t188, i64* %b
  %t189 = getelementptr [29 x i8], [29 x i8]* @.str.16, i64 0, i64 0
  %t190 = call i64 @__val_tag_ptr(i8* %t189)
  %t191 = load i64, i64* %a
  %t192 = load i64, i64* %b
  %t193 = icmp eq i64 %t191, %t192
  %t194 = zext i1 %t193 to i64
  %t195 = call i64 @__val_tag_bool(i64 %t194)
  %t196 = call i64 @__val_untag_bool(i64 %t195)
  %t197 = call i64 @__bool_to_string(i64 %t196)
  %t198 = call i64 @__rt_tag_ptr(i64 %t197)
  %t199 = call i8* @__val_untag_ptr(i64 %t190)
  %t200 = call i8* @__val_untag_ptr(i64 %t198)
  %t201 = call i64 @strlen(i8* %t199)
  %t202 = call i64 @strlen(i8* %t200)
  %t203 = add i64 %t201, %t202
  %t204 = add i64 %t203, 1
  %t205 = call i8* @__sf_malloc(i64 %t204)
  call i8* @strcpy(i8* %t205, i8* %t199)
  call i8* @strcat(i8* %t205, i8* %t200)
  %t206 = ptrtoint i8* %t205 to i64
  %t207 = call i64 @__string_intern(i64 %t206)
  %t208 = inttoptr i64 %t207 to i8*
  %t209 = call i64 @__val_tag_ptr(i8* %t208)
  %t210 = call i64 @__io_println(i64 %t209)
  call void @__gc_pop_roots(i64 2)
  ret i64 0
}

define i64 @__class_parent_tag(i64 %tag) {
entry:
  ret i64 0
}

define i1 @__class_is_a(i64 %tag, i64 %target) {
entry:
  %z = icmp eq i64 %tag, 0
  br i1 %z, label %cia.no, label %cia.tchk
cia.tchk:
  %tz = icmp eq i64 %target, 0
  br i1 %tz, label %cia.no, label %cia.self
cia.self:
  %hit = icmp eq i64 %tag, %target
  br i1 %hit, label %cia.yes, label %cia.no
cia.yes:
  ret i1 1
cia.no:
  ret i1 0
}

define i64 @__saffron_entry() {
entry:
  call void @__gc_enable()
  %t1 = call i64 @__saffron_main()
  ret i64 0
}

define i32 @main(i32 %argc, i8** %argv) {
entry:
  store i32 %argc, i32* @__argc
  store i8** %argv, i8*** @__argv
  call i64 @__saffron_entry()
  ret i32 0
}
