; Generated by Saffron LLVM compiler
target triple = "arm64-apple-macosx15.0.0"

@.str.0 = private unnamed_addr constant [6 x i8] c"Some(\00"
@.str.1 = private unnamed_addr constant [2 x i8] c")\00"
@.str.2 = private unnamed_addr constant [5 x i8] c"None\00"
@.str.3 = private unnamed_addr constant [8 x i8] c"Unknown\00"
@.str.4 = private unnamed_addr constant [3 x i8] c"eq\00"
@.str.5 = private unnamed_addr constant [3 x i8] c"ne\00"
@.str.6 = private unnamed_addr constant [4 x i8] c"neq\00"
@.str.7 = private unnamed_addr constant [4 x i8] c"nne\00"
@.str.8 = private unnamed_addr constant [5 x i8] c"a!=b\00"
@.str.9 = private unnamed_addr constant [5 x i8] c"a==b\00"

%Option = type { i8, [16 x i8] }

declare i32 @puts(i8*)
declare i32 @printf(i8*, ...)
declare i32 @snprintf(i8*, i64, i8*, ...)
declare i8* @malloc(i64)
declare i8* @realloc(i8*, i64)
declare void @free(i8*)
declare i64 @strlen(i8*)
declare i8* @strcpy(i8*, i8*)
declare i8* @strcat(i8*, i8*)
declare i8* @strstr(i8*, i8*)
declare i32 @strcmp(i8*, i8*)
declare i32 @strncmp(i8*, i8*, i64)
declare i64 @atol(i8*)
declare void @exit(i32)
declare i8* @fopen(i8*, i8*)
declare i64 @fread(i8*, i64, i64, i8*)
declare i64 @fwrite(i8*, i64, i64, i8*)
declare i32 @fclose(i8*)
declare i32 @fseek(i8*, i64, i32)
declare i64 @ftell(i8*)
declare i8* @strtok(i8*, i8*)
declare i32 @pclose(i8*)
declare i8* @popen(i8*, i8*)
declare i8* @fgets(i8*, i32, i8*)
declare void @llvm.memcpy.p0i8.p0i8.i64(i8*, i8*, i64, i1)
declare i32 @setjmp(i8*) returns_twice
declare void @longjmp(i8*, i32) noreturn
declare void @__io_println_str(i64)
declare void @__io_println_int(i64)
declare void @__io_println_bool(i64)
declare void @__io_println_nil()
declare void @__io_println_any(i64)
declare void @__io_print_str(i64)
declare void @__io_print_int(i64)
declare i64 @__any_to_string(i64)
declare i64 @__bool_to_string(i64)
declare i64 @__nil_to_string()

declare i64 @__float_to_string(i64)
declare i64 @__string_eq(i64, i64)
declare i64 @__string_ne(i64, i64)
declare i64 @__any_eq(i64, i64)
declare i64 @__any_ne(i64, i64)
declare i64 @__string_intern(i64)
; --- NaN-boxing value helpers ---
declare i64 @__val_tag_int(i64)
declare i64 @__val_untag_int(i64)
declare i64 @__val_tag_ptr(i8*)
declare i64 @__val_tag_ptr_nullable(i8*)
declare i8* @__val_untag_ptr(i64)
declare i64 @__val_tag_float(double)
declare double @__val_untag_float(i64)
declare i64 @__val_tag_bool(i64)
declare i64 @__val_untag_bool(i64)
declare i64 @__rt_tag_ptr(i64)
declare double @strtod(i8*, i8*)
declare double @llvm.floor.f64(double)

declare i64 @__division_error()
declare i64 @__null_pointer_error()
declare i64 @__runtime_error(i64)
declare i64 @__runtime_error_fatal(i64)

@.fmt.ld = linkonce_odr unnamed_addr constant [4 x i8] c"%ld\00"
@.str.empty = linkonce_odr unnamed_addr constant [1 x i8] c"\00"
@.str.rb = linkonce_odr unnamed_addr constant [2 x i8] c"r\00"
@.str.wb = linkonce_odr unnamed_addr constant [2 x i8] c"w\00"
@.str.r = linkonce_odr unnamed_addr constant [2 x i8] c"r\00"
@__argc = weak global i32 0
@__argv = weak global i8** null
@__exception_value = weak global i64 0
@__jmp_buf_current = weak global i8* null

; List = { count, capacity, data* }
%List = type { i64, i64, i64* }
; Map = { count, capacity, keys*, values* }
%Map = type { i64, i64, i64*, i64* }

; --- Runtime declarations ---
%SB = type { i64, i64, i8* }

declare i64 @__list_new()
declare i64 @__list_push(i64, i64)
declare i64 @__list_get(i64, i64)
declare i64 @__list_set(i64, i64, i64)
declare i64 @__list_length(i64)
declare i64 @__list_pop(i64)
declare i64 @__list_remove(i64, i64)
declare i64 @__list_slice(i64, i64, i64)
declare i64 @StringBuilder()
declare i64 @__sb_append(i64, i64)
declare i64 @__sb_to_string(i64)
declare i64 @__safe_strcmp(i64, i64)
declare i64 @__map_new()
declare i64 @__map_set(i64, i64, i64)
declare i64 @__map_get(i64, i64)
declare i64 @__map_has(i64, i64)
declare i64 @__map_keys(i64)
declare i64 @__str_ends_with(i64, i64)
declare i64 @__str_split(i64, i64)
declare i64 @__str_replace(i64, i64, i64)
declare i64 @__int_to_string(i64)
declare i64 @__list_join(i64, i64)
declare i64 @__join_append(i64, i64, i64, i64, i64)
declare i64 @__list_contains(i64, i64)
declare i64 @__io_read_file(i64)
declare i64 @__io_write_file(i64, i64)
declare i64 @__io_file_exists(i64)
declare i64 @__io_mkdir(i64)
declare i64 @__io_walk_dir(i64)
declare i64 @__io_append_file(i64, i64)
declare i64 @__io_file_size(i64)
declare i64 @__io_read_binary(i64, i64, i64)
declare i64 @__io_is_dir(i64)
declare i64 @__io_rename(i64, i64)
declare i64 @__io_delete_file(i64)
declare i64 @__os_set_env(i64, i64)
declare i64 @__os_home()
declare i64 @__io_read_stdin(i64)
declare i64 @__io_readline()
declare i64 @__os_exec(i64)
declare i64 @__os_args()
declare i64 @__os_cwd()
declare i64 @__os_path_sep()
declare i64 @__os_platform()
declare i64 @__os_env(i64)
declare i64 @__os_system(i64)
declare i64 @__str_get(i64, i64)
declare i64 @__io_println(i64)
declare i64 @__io_print(i64)
declare i64 @__any_iter_get(i64, i64)
@__debug_location = external global i8*
declare i64 @__val_nil()
declare i1 @__val_is_int(i64)
declare i1 @__val_is_float(i64)
declare i1 @__val_is_string(i64)
declare i1 @__val_is_bool(i64)
declare i1 @__val_is_nil(i64)
declare i1 @__val_is_list(i64)
declare i1 @__val_is_map(i64)
declare i64 @__val_class_tag(i64)

; --- GC runtime ---
declare void @__gc_enable()
declare void @__gc_disable()
declare void @__gc_collect()
declare void @__gc_set_threshold(i64)
declare i64 @__gc_stat_alloc_count()
declare i64 @__gc_stat_total_bytes()
declare i64 @__gc_stat_collections()
declare i64 @__gc_stat_freed_bytes()
declare i64 @__gc_stat_threshold()
declare void @__gc_debug_stats()
declare i64 @__gc_alloc(i64, i64)
declare i64 @__gc_alloc_zeroed(i64, i64)
declare i64 @__gc_realloc(i64, i64, i64)
declare void @__gc_push_root(i64)
declare void @__gc_pop_roots(i64)
declare i64 @__gc_shadow_stack_depth()
declare i64 @__gc_list_new()
declare void @__gc_list_push(i64, i64)
declare i64 @__gc_map_new()
declare i64 @__gc_stringbuilder_new()
declare i64 @__gc_string_alloc(i64)
declare i64 @__gc_closure_new(i64, i64)
declare i64 @__gc_env_alloc(i64)
declare i64 @__gc_instance_alloc(i64)
declare i64 @__gc_get_type_tag(i64)
declare i8* @__sf_malloc(i64)

; --- Scheduler runtime ---
declare double @sf_time_now()
declare i64 @sf_tcp_poll(i64, i64, i64)
declare void @__sched_coro_resume(i64)
declare i64 @__sched_coro_done(i64)
declare void @__sched_coro_destroy(i64)
declare i64 @__sched_get_yield_reason()
declare i64 @__sched_get_yield_arg()
declare i64 @__sched_get_task_result()
declare void @__sched_reset_yield()
declare void @__sched_store_result(i64, i64)
declare i64 @__sched_get_stored_result(i64)
declare i64 @__sched_has_stored_result(i64)

define linkonce_odr i64 @Some(i64 %f0) {
entry:
  %t1 = call i8* @__sf_malloc(i64 16)
  %t2 = bitcast i8* %t1 to [2 x i64]*
  %t3 = getelementptr [2 x i64], [2 x i64]* %t2, i64 0, i64 0
  store i64 0, i64* %t3
  %t4 = getelementptr [2 x i64], [2 x i64]* %t2, i64 0, i64 1
  store i64 %f0, i64* %t4
  %t5 = ptrtoint [2 x i64]* %t2 to i64
  ret i64 %t5
}

define linkonce_odr i64 @Option__to_string(i64 %self) {
entry:
  %t1 = inttoptr i64 %self to i64*
  %t2 = load i64, i64* %t1
  switch i64 %t2, label %ets.end1 [ i64 0, label %ets.v2 i64 1, label %ets.v3 ]
ets.v2:
  %t3 = getelementptr [6 x i8], [6 x i8]* @.str.0, i64 0, i64 0
  %t4 = ptrtoint i8* %t3 to i64
  %t5 = call i64 @StringBuilder()
  call i64 @__sb_append(i64 %t5, i64 %t4)
  %t6 = inttoptr i64 %self to [2 x i64]*
  %t7 = getelementptr [2 x i64], [2 x i64]* %t6, i64 0, i64 1
  %t8 = load i64, i64* %t7
  %t9 = call i64 @__val_untag_int(i64 %t8)
  %t10 = call i64 @__int_to_string(i64 %t9)
  call i64 @__sb_append(i64 %t5, i64 %t10)
  %t11 = getelementptr [2 x i8], [2 x i8]* @.str.1, i64 0, i64 0
  %t12 = ptrtoint i8* %t11 to i64
  call i64 @__sb_append(i64 %t5, i64 %t12)
  %t13 = call i64 @__sb_to_string(i64 %t5)
  ret i64 %t13
ets.v3:
  %t14 = getelementptr [5 x i8], [5 x i8]* @.str.2, i64 0, i64 0
  %t15 = ptrtoint i8* %t14 to i64
  ret i64 %t15
ets.end1:
  %t16 = getelementptr [8 x i8], [8 x i8]* @.str.3, i64 0, i64 0
  %t17 = ptrtoint i8* %t16 to i64
  ret i64 %t17
}

define i64 @__saffron_main() {
entry:
  %a = alloca i64
  store i64 0, i64* %a
  %b = alloca i64
  store i64 0, i64* %b
  %t1 = ptrtoint i64* %a to i64
  call void @__gc_push_root(i64 %t1)
  %t2 = ptrtoint i64* %b to i64
  call void @__gc_push_root(i64 %t2)
  %t3 = call i8* @__sf_malloc(i64 16)
  %t4 = bitcast i8* %t3 to [2 x i64]*
  %t5 = getelementptr [2 x i64], [2 x i64]* %t4, i64 0, i64 0
  store i64 0, i64* %t5
  %t6 = add i64 0, 42
  %t7 = call i64 @__val_tag_int(i64 %t6)
  %t8 = getelementptr [2 x i64], [2 x i64]* %t4, i64 0, i64 1
  store i64 %t7, i64* %t8
  %t9 = ptrtoint [2 x i64]* %t4 to i64
  store i64 %t9, i64* %a
  %t10 = call i8* @__sf_malloc(i64 16)
  %t11 = bitcast i8* %t10 to [2 x i64]*
  %t12 = getelementptr [2 x i64], [2 x i64]* %t11, i64 0, i64 0
  store i64 0, i64* %t12
  %t13 = add i64 0, 42
  %t14 = call i64 @__val_tag_int(i64 %t13)
  %t15 = getelementptr [2 x i64], [2 x i64]* %t11, i64 0, i64 1
  store i64 %t14, i64* %t15
  %t16 = ptrtoint [2 x i64]* %t11 to i64
  store i64 %t16, i64* %b
  %t17 = load i64, i64* %a
  %t18 = load i64, i64* %b
  ; MARKER-SITE-A-EQ-BLOCK
  %t19 = icmp eq i64 %t17, %t18
  %t20 = zext i1 %t19 to i64
  %t21 = call i64 @__val_tag_bool(i64 %t20)
  %t22 = trunc i64 %t21 to i1
  br i1 %t22, label %then5, label %else6
then5:
  %t23 = getelementptr [3 x i8], [3 x i8]* @.str.4, i64 0, i64 0
  %t24 = call i64 @__val_tag_ptr(i8* %t23)
  %t25 = call i64 @__io_println(i64 %t24)
  br label %endif4
else6:
  %t26 = getelementptr [3 x i8], [3 x i8]* @.str.5, i64 0, i64 0
  %t27 = call i64 @__val_tag_ptr(i8* %t26)
  %t28 = call i64 @__io_println(i64 %t27)
  br label %endif4
endif4:
  %t29 = call i8* @__sf_malloc(i64 8)
  %t30 = bitcast i8* %t29 to [1 x i64]*
  %t31 = getelementptr [1 x i64], [1 x i64]* %t30, i64 0, i64 0
  store i64 1, i64* %t31
  %t32 = ptrtoint [1 x i64]* %t30 to i64
  %t33 = call i8* @__sf_malloc(i64 8)
  %t34 = bitcast i8* %t33 to [1 x i64]*
  %t35 = getelementptr [1 x i64], [1 x i64]* %t34, i64 0, i64 0
  store i64 1, i64* %t35
  %t36 = ptrtoint [1 x i64]* %t34 to i64
  ; MARKER-SITE-A-EQ-BLOCK
  %t37 = icmp eq i64 %t32, %t36
  %t38 = zext i1 %t37 to i64
  %t39 = call i64 @__val_tag_bool(i64 %t38)
  %t40 = trunc i64 %t39 to i1
  br i1 %t40, label %then8, label %else9
then8:
  %t41 = getelementptr [4 x i8], [4 x i8]* @.str.6, i64 0, i64 0
  %t42 = call i64 @__val_tag_ptr(i8* %t41)
  %t43 = call i64 @__io_println(i64 %t42)
  br label %endif7
else9:
  %t44 = getelementptr [4 x i8], [4 x i8]* @.str.7, i64 0, i64 0
  %t45 = call i64 @__val_tag_ptr(i8* %t44)
  %t46 = call i64 @__io_println(i64 %t45)
  br label %endif7
endif7:
  %t47 = load i64, i64* %a
  %t48 = load i64, i64* %b
  ; MARKER-SITE-A-EQ-BLOCK
  %t49 = icmp ne i64 %t47, %t48
  %t50 = zext i1 %t49 to i64
  %t51 = call i64 @__val_tag_bool(i64 %t50)
  %t52 = trunc i64 %t51 to i1
  br i1 %t52, label %then11, label %else12
then11:
  %t53 = getelementptr [5 x i8], [5 x i8]* @.str.8, i64 0, i64 0
  %t54 = call i64 @__val_tag_ptr(i8* %t53)
  %t55 = call i64 @__io_println(i64 %t54)
  br label %endif10
else12:
  %t56 = getelementptr [5 x i8], [5 x i8]* @.str.9, i64 0, i64 0
  %t57 = call i64 @__val_tag_ptr(i8* %t56)
  %t58 = call i64 @__io_println(i64 %t57)
  br label %endif10
endif10:
  call void @__gc_pop_roots(i64 2)
  ret i64 0
}

define i64 @__class_parent_tag(i64 %tag) {
entry:
  ret i64 0
}

define i1 @__class_is_a(i64 %tag, i64 %target) {
entry:
  %z = icmp eq i64 %tag, 0
  br i1 %z, label %cia.no, label %cia.tchk
cia.tchk:
  %tz = icmp eq i64 %target, 0
  br i1 %tz, label %cia.no, label %cia.self
cia.self:
  %hit = icmp eq i64 %tag, %target
  br i1 %hit, label %cia.yes, label %cia.no
cia.yes:
  ret i1 1
cia.no:
  ret i1 0
}

define i64 @__saffron_entry() {
entry:
  call void @__gc_enable()
  %t1 = call i64 @__saffron_main()
  ret i64 0
}

define i32 @main(i32 %argc, i8** %argv) {
entry:
  store i32 %argc, i32* @__argc
  store i8** %argv, i8*** @__argv
  call i64 @__saffron_entry()
  ret i32 0
}
