; Generated by Saffron LLVM compiler
target triple = "arm64-apple-macosx15.0.0"

@.str.0 = private unnamed_addr constant [8 x i8] c"Circle(\00"
@.str.1 = private unnamed_addr constant [2 x i8] c")\00"
@.str.2 = private unnamed_addr constant [8 x i8] c"Square(\00"
@.str.3 = private unnamed_addr constant [2 x i8] c")\00"
@.str.4 = private unnamed_addr constant [8 x i8] c"Unknown\00"
@.str.5 = private unnamed_addr constant [2 x i8] c"a\00"
@.str.6 = private unnamed_addr constant [2 x i8] c"b\00"
@.str.7 = private unnamed_addr constant [2 x i8] c"c\00"
@.str.8 = private unnamed_addr constant [2 x i8] c"a\00"
@.str.9 = private unnamed_addr constant [2 x i8] c"b\00"
@.str.10 = private unnamed_addr constant [2 x i8] c"c\00"
@.str.11 = private unnamed_addr constant [43 x i8] c"tagged Circle(2)==Circle(3) (want false): \00"
@.str.12 = private unnamed_addr constant [43 x i8] c"tagged Circle(2)==Square(2) (want false): \00"
@.str.13 = private unnamed_addr constant [2 x i8] c"d\00"
@.str.14 = private unnamed_addr constant [2 x i8] c"d\00"
@.str.15 = private unnamed_addr constant [43 x i8] c"tagged Circle(2)==Circle(2) (want true):  \00"

%Shape = type { i8, [16 x i8] }

declare i32 @puts(i8*)
declare i32 @printf(i8*, ...)
declare i32 @snprintf(i8*, i64, i8*, ...)
declare i8* @malloc(i64)
declare i8* @realloc(i8*, i64)
declare void @free(i8*)
declare i64 @strlen(i8*)
declare i8* @strcpy(i8*, i8*)
declare i8* @strcat(i8*, i8*)
declare i8* @strstr(i8*, i8*)
declare i32 @strcmp(i8*, i8*)
declare i32 @strncmp(i8*, i8*, i64)
declare i64 @atol(i8*)
declare void @exit(i32)
declare i8* @fopen(i8*, i8*)
declare i64 @fread(i8*, i64, i64, i8*)
declare i64 @fwrite(i8*, i64, i64, i8*)
declare i32 @fclose(i8*)
declare i32 @fseek(i8*, i64, i32)
declare i64 @ftell(i8*)
declare i8* @strtok(i8*, i8*)
declare i32 @pclose(i8*)
declare i8* @popen(i8*, i8*)
declare i8* @fgets(i8*, i32, i8*)
declare void @llvm.memcpy.p0i8.p0i8.i64(i8*, i8*, i64, i1)
declare i32 @setjmp(i8*) returns_twice
declare void @longjmp(i8*, i32) noreturn
declare void @__io_println_str(i64)
declare void @__io_println_int(i64)
declare void @__io_println_bool(i64)
declare void @__io_println_nil()
declare void @__io_println_any(i64)
declare void @__io_print_str(i64)
declare void @__io_print_int(i64)
declare i64 @__any_to_string(i64)
declare i64 @__bool_to_string(i64)
declare i64 @__nil_to_string()

declare i64 @__float_to_string(i64)
declare i64 @__string_eq(i64, i64)
declare i64 @__string_ne(i64, i64)
declare i64 @__any_eq(i64, i64)
declare i64 @__any_ne(i64, i64)
declare i64 @__string_intern(i64)
; --- NaN-boxing value helpers ---
declare i64 @__val_tag_int(i64)
declare i64 @__val_untag_int(i64)
declare i64 @__val_tag_ptr(i8*)
declare i64 @__val_tag_ptr_nullable(i8*)
declare i8* @__val_untag_ptr(i64)
declare i64 @__val_tag_float(double)
declare double @__val_untag_float(i64)
declare i64 @__val_tag_bool(i64)
declare i64 @__val_untag_bool(i64)
declare i64 @__rt_tag_ptr(i64)
declare double @strtod(i8*, i8*)
declare double @llvm.floor.f64(double)

declare i64 @__division_error()
declare i64 @__null_pointer_error()
declare i64 @__runtime_error(i64)
declare i64 @__runtime_error_fatal(i64)

@.fmt.ld = linkonce_odr unnamed_addr constant [4 x i8] c"%ld\00"
@.str.empty = linkonce_odr unnamed_addr constant [1 x i8] c"\00"
@.str.rb = linkonce_odr unnamed_addr constant [2 x i8] c"r\00"
@.str.wb = linkonce_odr unnamed_addr constant [2 x i8] c"w\00"
@.str.r = linkonce_odr unnamed_addr constant [2 x i8] c"r\00"
@__argc = weak global i32 0
@__argv = weak global i8** null
@__exception_value = weak global i64 0
@__jmp_buf_current = weak global i8* null

; List = { count, capacity, data* }
%List = type { i64, i64, i64* }
; Map = { count, capacity, keys*, values* }
%Map = type { i64, i64, i64*, i64* }

; --- Runtime declarations ---
%SB = type { i64, i64, i8* }

declare i64 @__list_new()
declare i64 @__list_push(i64, i64)
declare i64 @__list_get(i64, i64)
declare i64 @__list_set(i64, i64, i64)
declare i64 @__list_length(i64)
declare i64 @__list_pop(i64)
declare i64 @__list_remove(i64, i64)
declare i64 @__list_slice(i64, i64, i64)
declare i64 @StringBuilder()
declare i64 @__sb_append(i64, i64)
declare i64 @__sb_to_string(i64)
declare i64 @__safe_strcmp(i64, i64)
declare i64 @__map_new()
declare i64 @__map_set(i64, i64, i64)
declare i64 @__map_get(i64, i64)
declare i64 @__map_has(i64, i64)
declare i64 @__map_keys(i64)
declare i64 @__str_ends_with(i64, i64)
declare i64 @__str_split(i64, i64)
declare i64 @__str_replace(i64, i64, i64)
declare i64 @__int_to_string(i64)
declare i64 @__list_join(i64, i64)
declare i64 @__join_append(i64, i64, i64, i64, i64)
declare i64 @__list_contains(i64, i64)
declare i64 @__io_read_file(i64)
declare i64 @__io_write_file(i64, i64)
declare i64 @__io_file_exists(i64)
declare i64 @__io_mkdir(i64)
declare i64 @__io_walk_dir(i64)
declare i64 @__io_append_file(i64, i64)
declare i64 @__io_file_size(i64)
declare i64 @__io_read_binary(i64, i64, i64)
declare i64 @__io_is_dir(i64)
declare i64 @__io_rename(i64, i64)
declare i64 @__io_delete_file(i64)
declare i64 @__os_set_env(i64, i64)
declare i64 @__os_home()
declare i64 @__io_read_stdin(i64)
declare i64 @__io_readline()
declare i64 @__os_exec(i64)
declare i64 @__os_args()
declare i64 @__os_cwd()
declare i64 @__os_path_sep()
declare i64 @__os_platform()
declare i64 @__os_env(i64)
declare i64 @__os_system(i64)
declare i64 @__str_get(i64, i64)
declare i64 @__io_println(i64)
declare i64 @__io_print(i64)
declare i64 @__any_iter_get(i64, i64)
@__debug_location = external global i8*
declare i64 @__val_nil()
declare i1 @__val_is_int(i64)
declare i1 @__val_is_float(i64)
declare i1 @__val_is_string(i64)
declare i1 @__val_is_bool(i64)
declare i1 @__val_is_nil(i64)
declare i1 @__val_is_list(i64)
declare i1 @__val_is_map(i64)
declare i64 @__val_class_tag(i64)

; --- GC runtime ---
declare void @__gc_enable()
declare void @__gc_disable()
declare void @__gc_collect()
declare void @__gc_set_threshold(i64)
declare i64 @__gc_stat_alloc_count()
declare i64 @__gc_stat_total_bytes()
declare i64 @__gc_stat_collections()
declare i64 @__gc_stat_freed_bytes()
declare i64 @__gc_stat_threshold()
declare void @__gc_debug_stats()
declare i64 @__gc_alloc(i64, i64)
declare i64 @__gc_alloc_zeroed(i64, i64)
declare i64 @__gc_realloc(i64, i64, i64)
declare void @__gc_push_root(i64)
declare void @__gc_pop_roots(i64)
declare i64 @__gc_shadow_stack_depth()
declare i64 @__gc_list_new()
declare void @__gc_list_push(i64, i64)
declare i64 @__gc_map_new()
declare i64 @__gc_stringbuilder_new()
declare i64 @__gc_string_alloc(i64)
declare i64 @__gc_closure_new(i64, i64)
declare i64 @__gc_env_alloc(i64)
declare i64 @__gc_instance_alloc(i64)
declare i64 @__gc_get_type_tag(i64)
declare i8* @__sf_malloc(i64)

; --- Scheduler runtime ---
declare double @sf_time_now()
declare i64 @sf_tcp_poll(i64, i64, i64)
declare void @__sched_coro_resume(i64)
declare i64 @__sched_coro_done(i64)
declare void @__sched_coro_destroy(i64)
declare i64 @__sched_get_yield_reason()
declare i64 @__sched_get_yield_arg()
declare i64 @__sched_get_task_result()
declare void @__sched_reset_yield()
declare void @__sched_store_result(i64, i64)
declare i64 @__sched_get_stored_result(i64)
declare i64 @__sched_has_stored_result(i64)

define linkonce_odr i64 @Circle(i64 %f0) {
entry:
  %t1 = call i8* @__sf_malloc(i64 16)
  %t2 = bitcast i8* %t1 to [2 x i64]*
  %t3 = getelementptr [2 x i64], [2 x i64]* %t2, i64 0, i64 0
  store i64 0, i64* %t3
  %t4 = getelementptr [2 x i64], [2 x i64]* %t2, i64 0, i64 1
  store i64 %f0, i64* %t4
  %t5 = ptrtoint [2 x i64]* %t2 to i64
  ret i64 %t5
}

define linkonce_odr i64 @Square(i64 %f0) {
entry:
  %t1 = call i8* @__sf_malloc(i64 16)
  %t2 = bitcast i8* %t1 to [2 x i64]*
  %t3 = getelementptr [2 x i64], [2 x i64]* %t2, i64 0, i64 0
  store i64 1, i64* %t3
  %t4 = getelementptr [2 x i64], [2 x i64]* %t2, i64 0, i64 1
  store i64 %f0, i64* %t4
  %t5 = ptrtoint [2 x i64]* %t2 to i64
  ret i64 %t5
}

define linkonce_odr i64 @Shape__to_string(i64 %self) {
entry:
  %t1 = inttoptr i64 %self to i64*
  %t2 = load i64, i64* %t1
  switch i64 %t2, label %ets.end1 [ i64 0, label %ets.v2 i64 1, label %ets.v3 ]
ets.v2:
  %t3 = getelementptr [8 x i8], [8 x i8]* @.str.0, i64 0, i64 0
  %t4 = ptrtoint i8* %t3 to i64
  %t5 = call i64 @StringBuilder()
  call i64 @__sb_append(i64 %t5, i64 %t4)
  %t6 = inttoptr i64 %self to [2 x i64]*
  %t7 = getelementptr [2 x i64], [2 x i64]* %t6, i64 0, i64 1
  %t8 = load i64, i64* %t7
  %t9 = call i64 @__float_to_string(i64 %t8)
  call i64 @__sb_append(i64 %t5, i64 %t9)
  %t10 = getelementptr [2 x i8], [2 x i8]* @.str.1, i64 0, i64 0
  %t11 = ptrtoint i8* %t10 to i64
  call i64 @__sb_append(i64 %t5, i64 %t11)
  %t12 = call i64 @__sb_to_string(i64 %t5)
  ret i64 %t12
ets.v3:
  %t13 = getelementptr [8 x i8], [8 x i8]* @.str.2, i64 0, i64 0
  %t14 = ptrtoint i8* %t13 to i64
  %t15 = call i64 @StringBuilder()
  call i64 @__sb_append(i64 %t15, i64 %t14)
  %t16 = inttoptr i64 %self to [2 x i64]*
  %t17 = getelementptr [2 x i64], [2 x i64]* %t16, i64 0, i64 1
  %t18 = load i64, i64* %t17
  %t19 = call i64 @__float_to_string(i64 %t18)
  call i64 @__sb_append(i64 %t15, i64 %t19)
  %t20 = getelementptr [2 x i8], [2 x i8]* @.str.3, i64 0, i64 0
  %t21 = ptrtoint i8* %t20 to i64
  call i64 @__sb_append(i64 %t15, i64 %t21)
  %t22 = call i64 @__sb_to_string(i64 %t15)
  ret i64 %t22
ets.end1:
  %t23 = getelementptr [8 x i8], [8 x i8]* @.str.4, i64 0, i64 0
  %t24 = ptrtoint i8* %t23 to i64
  ret i64 %t24
}

define i64 @__saffron_main() {
entry:
  %m = alloca i64
  store i64 0, i64* %m
  %a = alloca i64
  store i64 0, i64* %a
  %b = alloca i64
  store i64 0, i64* %b
  %c = alloca i64
  store i64 0, i64* %c
  %m2 = alloca i64
  store i64 0, i64* %m2
  %d = alloca i64
  store i64 0, i64* %d
  %t1 = ptrtoint i64* %m to i64
  call void @__gc_push_root(i64 %t1)
  %t2 = ptrtoint i64* %a to i64
  call void @__gc_push_root(i64 %t2)
  %t3 = ptrtoint i64* %b to i64
  call void @__gc_push_root(i64 %t3)
  %t4 = ptrtoint i64* %c to i64
  call void @__gc_push_root(i64 %t4)
  %t5 = ptrtoint i64* %m2 to i64
  call void @__gc_push_root(i64 %t5)
  %t6 = ptrtoint i64* %d to i64
  call void @__gc_push_root(i64 %t6)
  %t7 = call i64 @__map_new()
  store i64 %t7, i64* %m
  %t8 = load i64, i64* %m
  %t9 = getelementptr [2 x i8], [2 x i8]* @.str.5, i64 0, i64 0
  %t10 = call i64 @__val_tag_ptr(i8* %t9)
  %t11 = call i8* @__sf_malloc(i64 16)
  %t12 = bitcast i8* %t11 to [2 x i64]*
  %t13 = getelementptr [2 x i64], [2 x i64]* %t12, i64 0, i64 0
  store i64 0, i64* %t13
  %t14 = add i64 0, 2
  %t15 = call i64 @__val_tag_int(i64 %t14)
  %t16 = call double @__val_untag_float(i64 %t15)
  %t17 = call i64 @__val_tag_float(double %t16)
  %t18 = getelementptr [2 x i64], [2 x i64]* %t12, i64 0, i64 1
  store i64 %t17, i64* %t18
  %t19 = ptrtoint [2 x i64]* %t12 to i64
  %t20 = call i64 @__map_set(i64 %t8, i64 %t10, i64 %t19)
  %t21 = load i64, i64* %m
  %t22 = getelementptr [2 x i8], [2 x i8]* @.str.6, i64 0, i64 0
  %t23 = call i64 @__val_tag_ptr(i8* %t22)
  %t24 = call i8* @__sf_malloc(i64 16)
  %t25 = bitcast i8* %t24 to [2 x i64]*
  %t26 = getelementptr [2 x i64], [2 x i64]* %t25, i64 0, i64 0
  store i64 0, i64* %t26
  %t27 = add i64 0, 3
  %t28 = call i64 @__val_tag_int(i64 %t27)
  %t29 = call double @__val_untag_float(i64 %t28)
  %t30 = call i64 @__val_tag_float(double %t29)
  %t31 = getelementptr [2 x i64], [2 x i64]* %t25, i64 0, i64 1
  store i64 %t30, i64* %t31
  %t32 = ptrtoint [2 x i64]* %t25 to i64
  %t33 = call i64 @__map_set(i64 %t21, i64 %t23, i64 %t32)
  %t34 = load i64, i64* %m
  %t35 = getelementptr [2 x i8], [2 x i8]* @.str.7, i64 0, i64 0
  %t36 = call i64 @__val_tag_ptr(i8* %t35)
  %t37 = call i8* @__sf_malloc(i64 16)
  %t38 = bitcast i8* %t37 to [2 x i64]*
  %t39 = getelementptr [2 x i64], [2 x i64]* %t38, i64 0, i64 0
  store i64 1, i64* %t39
  %t40 = add i64 0, 2
  %t41 = call i64 @__val_tag_int(i64 %t40)
  %t42 = call double @__val_untag_float(i64 %t41)
  %t43 = call i64 @__val_tag_float(double %t42)
  %t44 = getelementptr [2 x i64], [2 x i64]* %t38, i64 0, i64 1
  store i64 %t43, i64* %t44
  %t45 = ptrtoint [2 x i64]* %t38 to i64
  %t46 = call i64 @__map_set(i64 %t34, i64 %t36, i64 %t45)
  %t47 = load i64, i64* %m
  %t48 = getelementptr [2 x i8], [2 x i8]* @.str.8, i64 0, i64 0
  %t49 = call i64 @__val_tag_ptr(i8* %t48)
  %t50 = call i64 @__map_get(i64 %t47, i64 %t49)
  store i64 %t50, i64* %a
  %t51 = load i64, i64* %m
  %t52 = getelementptr [2 x i8], [2 x i8]* @.str.9, i64 0, i64 0
  %t53 = call i64 @__val_tag_ptr(i8* %t52)
  %t54 = call i64 @__map_get(i64 %t51, i64 %t53)
  store i64 %t54, i64* %b
  %t55 = load i64, i64* %m
  %t56 = getelementptr [2 x i8], [2 x i8]* @.str.10, i64 0, i64 0
  %t57 = call i64 @__val_tag_ptr(i8* %t56)
  %t58 = call i64 @__map_get(i64 %t55, i64 %t57)
  store i64 %t58, i64* %c
  %t59 = getelementptr [43 x i8], [43 x i8]* @.str.11, i64 0, i64 0
  %t60 = call i64 @__val_tag_ptr(i8* %t59)
  %t61 = load i64, i64* %a
  %t62 = load i64, i64* %b
  %t63 = call i64 @__any_eq(i64 %t61, i64 %t62)
  %t64 = call i64 @__val_tag_bool(i64 %t63)
  %t65 = call i64 @__val_untag_bool(i64 %t64)
  %t66 = call i64 @__bool_to_string(i64 %t65)
  %t67 = call i64 @__rt_tag_ptr(i64 %t66)
  %t68 = call i8* @__val_untag_ptr(i64 %t60)
  %t69 = call i8* @__val_untag_ptr(i64 %t67)
  %t70 = call i64 @strlen(i8* %t68)
  %t71 = call i64 @strlen(i8* %t69)
  %t72 = add i64 %t70, %t71
  %t73 = add i64 %t72, 1
  %t74 = call i8* @__sf_malloc(i64 %t73)
  call i8* @strcpy(i8* %t74, i8* %t68)
  call i8* @strcat(i8* %t74, i8* %t69)
  %t75 = ptrtoint i8* %t74 to i64
  %t76 = call i64 @__string_intern(i64 %t75)
  %t77 = inttoptr i64 %t76 to i8*
  %t78 = call i64 @__val_tag_ptr(i8* %t77)
  %t79 = call i64 @__io_println(i64 %t78)
  %t80 = getelementptr [43 x i8], [43 x i8]* @.str.12, i64 0, i64 0
  %t81 = call i64 @__val_tag_ptr(i8* %t80)
  %t82 = load i64, i64* %a
  %t83 = load i64, i64* %c
  %t84 = call i64 @__any_eq(i64 %t82, i64 %t83)
  %t85 = call i64 @__val_tag_bool(i64 %t84)
  %t86 = call i64 @__val_untag_bool(i64 %t85)
  %t87 = call i64 @__bool_to_string(i64 %t86)
  %t88 = call i64 @__rt_tag_ptr(i64 %t87)
  %t89 = call i8* @__val_untag_ptr(i64 %t81)
  %t90 = call i8* @__val_untag_ptr(i64 %t88)
  %t91 = call i64 @strlen(i8* %t89)
  %t92 = call i64 @strlen(i8* %t90)
  %t93 = add i64 %t91, %t92
  %t94 = add i64 %t93, 1
  %t95 = call i8* @__sf_malloc(i64 %t94)
  call i8* @strcpy(i8* %t95, i8* %t89)
  call i8* @strcat(i8* %t95, i8* %t90)
  %t96 = ptrtoint i8* %t95 to i64
  %t97 = call i64 @__string_intern(i64 %t96)
  %t98 = inttoptr i64 %t97 to i8*
  %t99 = call i64 @__val_tag_ptr(i8* %t98)
  %t100 = call i64 @__io_println(i64 %t99)
  %t101 = call i64 @__map_new()
  store i64 %t101, i64* %m2
  %t102 = load i64, i64* %m2
  %t103 = getelementptr [2 x i8], [2 x i8]* @.str.13, i64 0, i64 0
  %t104 = call i64 @__val_tag_ptr(i8* %t103)
  %t105 = call i8* @__sf_malloc(i64 16)
  %t106 = bitcast i8* %t105 to [2 x i64]*
  %t107 = getelementptr [2 x i64], [2 x i64]* %t106, i64 0, i64 0
  store i64 0, i64* %t107
  %t108 = add i64 0, 2
  %t109 = call i64 @__val_tag_int(i64 %t108)
  %t110 = call double @__val_untag_float(i64 %t109)
  %t111 = call i64 @__val_tag_float(double %t110)
  %t112 = getelementptr [2 x i64], [2 x i64]* %t106, i64 0, i64 1
  store i64 %t111, i64* %t112
  %t113 = ptrtoint [2 x i64]* %t106 to i64
  %t114 = call i64 @__map_set(i64 %t102, i64 %t104, i64 %t113)
  %t115 = load i64, i64* %m2
  %t116 = getelementptr [2 x i8], [2 x i8]* @.str.14, i64 0, i64 0
  %t117 = call i64 @__val_tag_ptr(i8* %t116)
  %t118 = call i64 @__map_get(i64 %t115, i64 %t117)
  store i64 %t118, i64* %d
  %t119 = getelementptr [43 x i8], [43 x i8]* @.str.15, i64 0, i64 0
  %t120 = call i64 @__val_tag_ptr(i8* %t119)
  %t121 = load i64, i64* %a
  %t122 = load i64, i64* %d
  %t123 = call i64 @__any_eq(i64 %t121, i64 %t122)
  %t124 = call i64 @__val_tag_bool(i64 %t123)
  %t125 = call i64 @__val_untag_bool(i64 %t124)
  %t126 = call i64 @__bool_to_string(i64 %t125)
  %t127 = call i64 @__rt_tag_ptr(i64 %t126)
  %t128 = call i8* @__val_untag_ptr(i64 %t120)
  %t129 = call i8* @__val_untag_ptr(i64 %t127)
  %t130 = call i64 @strlen(i8* %t128)
  %t131 = call i64 @strlen(i8* %t129)
  %t132 = add i64 %t130, %t131
  %t133 = add i64 %t132, 1
  %t134 = call i8* @__sf_malloc(i64 %t133)
  call i8* @strcpy(i8* %t134, i8* %t128)
  call i8* @strcat(i8* %t134, i8* %t129)
  %t135 = ptrtoint i8* %t134 to i64
  %t136 = call i64 @__string_intern(i64 %t135)
  %t137 = inttoptr i64 %t136 to i8*
  %t138 = call i64 @__val_tag_ptr(i8* %t137)
  %t139 = call i64 @__io_println(i64 %t138)
  call void @__gc_pop_roots(i64 6)
  ret i64 0
}

define i64 @__class_parent_tag(i64 %tag) {
entry:
  ret i64 0
}

define i1 @__class_is_a(i64 %tag, i64 %target) {
entry:
  %z = icmp eq i64 %tag, 0
  br i1 %z, label %cia.no, label %cia.tchk
cia.tchk:
  %tz = icmp eq i64 %target, 0
  br i1 %tz, label %cia.no, label %cia.self
cia.self:
  %hit = icmp eq i64 %tag, %target
  br i1 %hit, label %cia.yes, label %cia.no
cia.yes:
  ret i1 1
cia.no:
  ret i1 0
}

define i64 @__saffron_entry() {
entry:
  call void @__gc_enable()
  %t1 = call i64 @__saffron_main()
  ret i64 0
}

define i32 @main(i32 %argc, i8** %argv) {
entry:
  store i32 %argc, i32* @__argc
  store i8** %argv, i8*** @__argv
  call i64 @__saffron_entry()
  ret i32 0
}
