[package]
name = "turmeric-demo"
version = "0.1.0"
entry = "src/main.sf"
target = "wasm"

[dependencies]
turmeric = { path = "../../turmeric" }

[scripts]
build = "turmeric-build"
dev = "turmeric-dev"
