[package]
name = "turmeric"
version = "0.1.0"
description = "Reactive web framework for Saffron targeting WASM"
type = "library"
entry = "src/index.sf"
authors = ["henry232323"]
target = "wasm32"

[dependencies]

[scripts]
generate = "saffron run tools/generate_types.sf"
