// Auto-generated by turmeric-build — do not edit
const decoder = new TextDecoder();
const handles = [null];
let instance;

function allocHandle(el) { handles.push(el); return handles.length - 1; }

// DOM handles are declared `Float` on the Saffron side, so a handle we hand back
// as a bare integer comes to us NaN-box tagged (TAG_INT | handle) on the next
// call in. Masking off the payload accepts both shapes: a tagged handle and a
// plain integer both mask down to the same index.
const PAYLOAD_MASK = 0x0000FFFFFFFFFFFFn;
function handleIndex(id) {
    return Number(BigInt(id) & PAYLOAD_MASK);
}
function getHandle(id) { return handles[handleIndex(id)] || null; }

// Decode a NaN-boxed i64 to a JS number. A `Float` parameter arrives as raw
// double bits when it holds a non-integral value (a 1.0 delay comes through as
// 0x3FF0000000000000), and as TAG_INT|payload when the producer tagged it, so
// both cases have to be distinguished by tag rather than assumed.
const TAG_MASK = 0xFFFF000000000000n;
const TAG_INT_BITS = 0x7FF9000000000000n;
const _f64buf = new DataView(new ArrayBuffer(8));
function valToNumber(v) {
    const bits = BigInt(v);
    if ((bits & TAG_MASK) === TAG_INT_BITS) return Number(bits & PAYLOAD_MASK);
    _f64buf.setBigUint64(0, bits & 0xFFFFFFFFFFFFFFFFn);
    const d = _f64buf.getFloat64(0);
    return Number.isNaN(d) ? Number(bits & PAYLOAD_MASK) : d;
}
function readCString(ptr) {
    const p = Number(ptr);
    if (p === 0) return "";
    const b = new Uint8Array(instance.exports.memory.buffer);
    let e = p;
    while (e < b.length && b[e] !== 0) e++;
    return decoder.decode(b.slice(p, e));
}

const _eventStack = [];

const imports = { env: new Proxy({
    js_log_str: (ptr) => console.log(readCString(ptr)),
    js_log_int: (n) => console.log(Number(n)),
    js_log_bool: (b) => console.log(Number(b) ? "true" : "false"),
    js_log_nil: () => console.log("nil"),
    js_dom_create_element: (tagPtr) => {
        return BigInt(allocHandle(document.createElement(readCString(tagPtr))));
    },
    js_dom_set_text: (handle, textPtr) => {
        const el = getHandle(handle);
        if (el) el.textContent = readCString(textPtr);
    },
    js_dom_set_attr: (handle, namePtr, valuePtr) => {
        const el = getHandle(handle);
        if (!el) return;
        const name = readCString(namePtr);
        const value = readCString(valuePtr);
        if (name === 'style') el.style.cssText = value;
        else if (name === 'class') el.className = value;
        else el.setAttribute(name, value);
    },
    js_dom_set_attribute: (handle, namePtr, valuePtr) => {
        const el = getHandle(handle);
        if (!el) return;
        const name = readCString(namePtr);
        const value = readCString(valuePtr);
        if (name === 'style') el.style.cssText = value;
        else if (name === 'class') el.className = value;
        else el.setAttribute(name, value);
    },
    js_dom_append_child: (parentHandle, childHandle) => {
        const parent = getHandle(parentHandle);
        const child = getHandle(childHandle);
        if (parent && child) parent.appendChild(child);
    },
    js_dom_remove_child: (parentHandle, childHandle) => {
        const parent = getHandle(parentHandle);
        const child = getHandle(childHandle);
        if (parent && child) parent.removeChild(child);
    },
    js_dom_insert_before: (parentHandle, nodeHandle, refHandle) => {
        const parent = getHandle(parentHandle);
        const node = getHandle(nodeHandle);
        const ref = getHandle(refHandle);
        if (parent && node) parent.insertBefore(node, ref);
    },
    js_dom_set_inner_html: (handle, htmlPtr) => {
        const el = getHandle(handle);
        if (el) el.innerHTML = readCString(htmlPtr);
    },
    js_dom_query_selector: (selectorPtr) => {
        const el = document.querySelector(readCString(selectorPtr));
        return el ? BigInt(allocHandle(el)) : 0n;
    },
    js_dom_add_event: (handle, eventPtr, callbackId) => {
        const el = getHandle(handle);
        if (!el) return;
        const name = readCString(eventPtr);
        el.addEventListener(name, (e) => {
            if (name === 'submit') e.preventDefault();
            _eventStack.push(e);
            try {
                if (_genericDispatch) _genericDispatch(callbackId);
            } catch (err) {
                // Silently ignore null function errors from nil on_click defaults
                if (!err.message || !err.message.includes('null function')) throw err;
            }
            _eventStack.pop();
        });
    },
    js_dom_add_event_listener: (handle, eventPtr, callbackId) => {
        const el = getHandle(handle);
        if (!el) return;
        const name = readCString(eventPtr);
        el.addEventListener(name, (e) => {
            if (name === 'submit') e.preventDefault();
            _eventStack.push(e);
            const typed = _findExport(`__dispatch_${name}`);
            if (typed) { typed(callbackId, 0n); }
            else if (_genericDispatch) { _genericDispatch(callbackId); }
            _eventStack.pop();
        });
    },
    js_dom_add_typed_event_listener: (handle, eventPtr, callbackId) => {
        const el = getHandle(handle);
        if (!el) return;
        const name = readCString(eventPtr);
        el.addEventListener(name, (e) => {
            if (name === 'submit') e.preventDefault();
            _eventStack.push(e);
            const typed = _findExport(`__dispatch_${name}`);
            if (typed) { typed(callbackId, 0n); }
            else if (_genericDispatch) { _genericDispatch(callbackId); }
            _eventStack.pop();
        });
    },
    js_dom_set_property: (handle, propPtr, valuePtr) => {
        const el = getHandle(handle);
        if (el) el[readCString(propPtr)] = readCString(valuePtr);
    },
    js_dom_set_bool_property: (handle, propPtr, value) => {
        const el = getHandle(handle);
        if (el) el[readCString(propPtr)] = !!Number(value);
    },
    js_event_get_float: (eventPtr, fieldPtr) => {
        const e = _eventStack[_eventStack.length - 1];
        if (!e) return 0n;
        const field = readCString(fieldPtr);
        const parts = field.split('.');
        let val = e;
        for (const p of parts) { val = val?.[p]; }
        // Return NaN-boxed float: raw double bits as i64
        const buf = new ArrayBuffer(8);
        new Float64Array(buf)[0] = Number(val) || 0;
        return new BigInt64Array(buf)[0];
    },
    js_event_get_string: (eventPtr, fieldPtr) => {
        const e = _eventStack[_eventStack.length - 1];
        if (!e) return 0n;
        const field = readCString(fieldPtr);
        const parts = field.split('.');
        let val = e;
        for (const p of parts) { val = val?.[p]; }
        const ptr = writeCString(String(val ?? ''));
        // Return raw pointer as i64 (codegen does inttoptr + tag_ptr on it)
        return BigInt(ptr) & 0xFFFFFFFFn;
    },
    js_event_get_bool: (eventPtr, fieldPtr) => {
        const e = _eventStack[_eventStack.length - 1];
        if (!e) return 0n;
        const field = readCString(fieldPtr);
        const parts = field.split('.');
        let val = e;
        for (const p of parts) { val = val?.[p]; }
        return val ? 1n : 0n;
    },
    js_event_prevent_default: () => { const e = _eventStack[_eventStack.length - 1]; if (e) e.preventDefault(); },
    js_event_stop_propagation: () => { const e = _eventStack[_eventStack.length - 1]; if (e) e.stopPropagation(); },
    memcpy: (dst, src, len) => {
        const b = new Uint8Array(instance.exports.memory.buffer);
        b.copyWithin(Number(dst), Number(src), Number(src) + Number(len));
        return dst;
    },
    // --- Navigation / Router FFI ---
    js_set_hash: (ptr) => { location.hash = readCString(ptr); },
    js_get_hash: () => writeCString(location.hash.replace(/^#\/?/, '') || '/'),
    js_push_state: (ptr) => history.pushState(null, '', readCString(ptr)),
    js_get_pathname: () => writeCString(location.pathname),
    js_fetch_json: (urlPtr, callbackId) => {
        const url = readCString(urlPtr);
        fetch(url).then(r => r.text()).then(text => {
            const fn = _findExport('__on_fetch_complete');
            if (fn) fn(callbackId, taggedString(text));
        }).catch(() => {
            const fn = _findExport('__on_fetch_complete');
            if (fn) fn(callbackId, taggedString('{"error":"fetch failed"}'));
        });
    },
    js_fetch_post: (urlPtr, bodyPtr, callbackId) => {
        const url = readCString(urlPtr);
        const body = readCString(bodyPtr);
        fetch(url, { method: 'POST', headers: { 'Content-Type': 'application/json' }, body })
            .then(r => r.text()).then(text => {
                const fn = _findExport('__on_fetch_complete');
                if (fn) fn(callbackId, taggedString(text));
            }).catch(() => {
                const fn = _findExport('__on_fetch_complete');
                if (fn) fn(callbackId, taggedString('{"error":"fetch failed"}'));
            });
    },
    js_fetch_post_auth: (urlPtr, bodyPtr, tokenPtr, callbackId) => {
        const url = readCString(urlPtr);
        const body = readCString(bodyPtr);
        const token = readCString(tokenPtr);
        fetch(url, { method: 'POST', headers: { 'Content-Type': 'application/json', 'Authorization': 'Bearer ' + token }, body })
            .then(r => r.text()).then(text => {
                const fn = _findExport('__on_fetch_complete');
                if (fn) fn(callbackId, taggedString(text));
            }).catch(() => {
                const fn = _findExport('__on_fetch_complete');
                if (fn) fn(callbackId, taggedString('{"error":"fetch failed"}'));
            });
    },
    js_set_timeout: (callbackId, ms) => {
        const id = setTimeout(() => {
            const fn = _findExport('__on_timeout');
            if (fn) fn(callbackId);
        }, valToNumber(ms));
        return BigInt(id);
    },
    js_clear_timeout: (timerId) => {
        clearTimeout(handleIndex(timerId));
    },
    js_set_interval: (callbackId, ms) => {
        const id = setInterval(() => {
            const fn = _findExport('__on_timeout');
            if (fn) fn(callbackId);
        }, valToNumber(ms));
        return BigInt(id);
    },
    js_clear_interval: (timerId) => {
        clearInterval(handleIndex(timerId));
    },
    __string_intern: (ptr) => ptr,
    __builtin_trap: () => { throw new Error("Saffron: exit/trap"); },
}, { get(t, p) { return t[p] || ((...args) => 0n); } }) };

function writeCString(str) {
    const encoder = new TextEncoder();
    const bytes = encoder.encode(str + '\0');
    const ptr = instance.exports.malloc(BigInt(bytes.length));
    const mem = new Uint8Array(instance.exports.memory.buffer);
    mem.set(bytes, Number(ptr));
    return ptr;
}

// Wrap a raw pointer as a NaN-boxed Saffron String value (TAG_PTR | payload).
//
// Imports declared `void*` (js_get_hash, js_event_get_string, ...) return a raw
// pointer and codegen emits the inttoptr + tag_ptr itself, so writeCString's
// result goes back untouched. Exported functions are the other direction:
// their params are already-tagged Saffron values and nothing on the wasm side
// tags them, so JS has to do it here. On wasm32 malloc is `(i64) -> i32`, which
// reaches JS as a Number — hence the BigInt conversion too.
const TAG_PTR = 0x7FF8000000000000n;
function taggedString(str) {
    return (BigInt(writeCString(str)) & 0xFFFFFFFFn) | TAG_PTR;
}

// Boot the WASM app
const response = await fetch('./app.wasm');
const wasmBytes = await response.arrayBuffer();
const result = await WebAssembly.instantiate(wasmBytes, imports);
instance = result.instance;

// Resolve exported WASM functions that may have module-prefixed symbol names.
// The compiler prefixes functions with their module path (e.g., turmeric_events___dispatch_submit).
// _findExport looks up by bare name first, then searches for a suffixed match.
const _exportCache = {};
function _findExport(name) {
    if (_exportCache[name] !== undefined) return _exportCache[name];
    let fn = instance.exports[name] || null;
    if (!fn) {
        for (const key of Object.keys(instance.exports)) {
            if (key === name || key.endsWith('_' + name)) { fn = instance.exports[key]; break; }
        }
    }
    _exportCache[name] = fn;
    return fn;
}

const _genericDispatch = _findExport('__dispatch_event');
function _getDispatch(eventName) {
    return _findExport(`__dispatch_${eventName}`) || _genericDispatch;
}

instance.exports._start();

// Browser navigation → WASM callback
const _onNavigate = _findExport('__on_navigate');
window.addEventListener('hashchange', () => { if (_onNavigate) _onNavigate(); });
window.addEventListener('popstate', () => { if (_onNavigate) _onNavigate(); });
