// Auto-generated by turmeric-build — do not edit.
//
// Thin loader shim: the real runtime lives in turmeric.js (one source of truth
// for DOM glue, event dispatch, and NaN-box marshalling). turmeric-build copies
// both this file and turmeric.js into the build output, so `import` resolves
// against the sibling file the app is served with.
//
// An app that needs extra imports or a custom wasm loader (e.g. the playground,
// which runs user-submitted wasm) should NOT fork this file — it should import
// { mount } from './turmeric.js' in its own public/app.js and pass options.
// See the mount() docblock in turmeric.js.
import { mount } from './turmeric.js';

mount('./app.wasm', '#app');
