[book]
title = "The Saffron Programming Language"
authors = ["henry232323"]
language = "en"
src = "src"

[build]
build-dir = "book"

[output.html]
default-theme = "navy"
preferred-dark-theme = "navy"
git-repository-url = "https://github.com/saffron-lang/saffron"
theme = "theme"
